// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:12151' | 'https://api.leios.dev' | (string & {});
};

export type GetPublicPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/packages';
};

export type GetPublicPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            owner_user_id: number;
            flags: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release: {
                amd64: string | null;
                arm64: string | null;
            };
            latest_testing_release: {
                amd64: string | null;
                arm64: string | null;
            };
        }>;
    };
};

export type GetPublicPackagesResponse = GetPublicPackagesResponses[keyof GetPublicPackagesResponses];

export type GetPublicPackagesByPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        repo?: 'leios-archive' | 'leios-testing' | 'leios-stable';
    };
    url: '/public/packages/{packageName}';
};

export type GetPublicPackagesByPackageNameErrors = {
    /**
     * Package not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package not found';
    };
};

export type GetPublicPackagesByPackageNameError = GetPublicPackagesByPackageNameErrors[keyof GetPublicPackagesByPackageNameErrors];

export type GetPublicPackagesByPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            package: {
                id: number;
                name: string;
                owner_user_id: number;
                flags: string | number | boolean | null | {
                    [key: string]: unknown;
                } | Array<unknown>;
                description: string;
                homepage_url: string;
                requires_patching: boolean;
                created_at: number;
                latest_stable_release: {
                    amd64: string | null;
                    arm64: string | null;
                };
                latest_testing_release: {
                    amd64: string | null;
                    arm64: string | null;
                };
            };
            releases: {
                'leios-archive': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                        all?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
                'leios-testing': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                        all?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
                'leios-stable': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                        all?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64' | 'all';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
            };
        };
    };
};

export type GetPublicPackagesByPackageNameResponse = GetPublicPackagesByPackageNameResponses[keyof GetPublicPackagesByPackageNameResponses];

export type GetPublicPackagesByPackageNameReleasesData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        repo?: 'leios-archive' | 'leios-testing' | 'leios-stable';
    };
    url: '/public/packages/{packageName}/releases';
};

export type GetPublicPackagesByPackageNameReleasesErrors = {
    /**
     * Package not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package not found';
    };
};

export type GetPublicPackagesByPackageNameReleasesError = GetPublicPackagesByPackageNameReleasesErrors[keyof GetPublicPackagesByPackageNameReleasesErrors];

export type GetPublicPackagesByPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: {
            'leios-archive': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                    all?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                };
            };
            'leios-testing': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                    all?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                };
            };
            'leios-stable': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                    all?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64' | 'all';
                        maintainer: string;
                        description: string;
                    };
                };
            };
        };
    };
};

export type GetPublicPackagesByPackageNameReleasesResponse = GetPublicPackagesByPackageNameReleasesResponses[keyof GetPublicPackagesByPackageNameReleasesResponses];

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid username or password';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body?: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type PostAuthResetPasswordRequestData = {
    body?: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password/request';
};

export type PostAuthResetPasswordRequestErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAuthResetPasswordRequestError = PostAuthResetPasswordRequestErrors[keyof PostAuthResetPasswordRequestErrors];

export type PostAuthResetPasswordRequestResponses = {
    /**
     * If the username exists, a password reset has been requested
     */
    200: {
        success: true;
        code: 200;
        message: 'If the username exists, a password reset has been requested';
        data: null;
    };
};

export type PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponses[keyof PostAuthResetPasswordRequestResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body?: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAccountApikeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type GetAccountApikeysResponses = {
    /**
     * API keys retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API keys retrieved successfully';
        data: Array<{
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        }>;
    };
};

export type GetAccountApikeysResponse = GetAccountApikeysResponses[keyof GetAccountApikeysResponses];

export type PostAccountApikeysData = {
    body?: {
        description: string;
        expires_at: '7d' | '30d' | '90d' | '180d' | '365d' | null;
    };
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type PostAccountApikeysErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAccountApikeysError = PostAccountApikeysErrors[keyof PostAccountApikeysErrors];

export type PostAccountApikeysResponses = {
    /**
     * API key created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key created successfully';
        data: {
            id: string;
            token: string;
        };
    };
};

export type PostAccountApikeysResponse = PostAccountApikeysResponses[keyof PostAccountApikeysResponses];

export type DeleteAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type DeleteAccountApikeysByApiKeyIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type DeleteAccountApikeysByApiKeyIdError = DeleteAccountApikeysByApiKeyIdErrors[keyof DeleteAccountApikeysByApiKeyIdErrors];

export type DeleteAccountApikeysByApiKeyIdResponses = {
    /**
     * API key deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key deleted successfully';
        data: null;
    };
};

export type DeleteAccountApikeysByApiKeyIdResponse = DeleteAccountApikeysByApiKeyIdResponses[keyof DeleteAccountApikeysByApiKeyIdResponses];

export type GetAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type GetAccountApikeysByApiKeyIdErrors = {
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type GetAccountApikeysByApiKeyIdError = GetAccountApikeysByApiKeyIdErrors[keyof GetAccountApikeysByApiKeyIdErrors];

export type GetAccountApikeysByApiKeyIdResponses = {
    /**
     * API key retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key retrieved successfully';
        data: {
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        };
    };
};

export type GetAccountApikeysByApiKeyIdResponse = GetAccountApikeysByApiKeyIdResponses[keyof GetAccountApikeysByApiKeyIdResponses];

export type GetDevPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dev/packages';
};

export type GetDevPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            owner_user_id: number;
            flags: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release: {
                amd64: string | null;
                arm64: string | null;
            };
            latest_testing_release: {
                amd64: string | null;
                arm64: string | null;
            };
        }>;
    };
};

export type GetDevPackagesResponse = GetDevPackagesResponses[keyof GetDevPackagesResponses];

export type PostDevPackagesData = {
    body?: {
        name: string;
        description: string;
        homepage_url: string;
        requires_patching?: boolean;
    };
    path?: never;
    query?: never;
    url: '/dev/packages';
};

export type PostDevPackagesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package with this name already exists';
    };
};

export type PostDevPackagesError = PostDevPackagesErrors[keyof PostDevPackagesErrors];

export type PostDevPackagesResponses = {
    /**
     * Package created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package created successfully';
        data: null;
    };
};

export type PostDevPackagesResponse = PostDevPackagesResponses[keyof PostDevPackagesResponses];

export type GetDevPackagesByPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}';
};

export type GetDevPackagesByPackageNameErrors = {
    /**
     * Package with specified Name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified Name not found';
    };
};

export type GetDevPackagesByPackageNameError = GetDevPackagesByPackageNameErrors[keyof GetDevPackagesByPackageNameErrors];

export type GetDevPackagesByPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            id: number;
            name: string;
            owner_user_id: number;
            flags: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release: {
                amd64: string | null;
                arm64: string | null;
            };
            latest_testing_release: {
                amd64: string | null;
                arm64: string | null;
            };
        };
    };
};

export type GetDevPackagesByPackageNameResponse = GetDevPackagesByPackageNameResponses[keyof GetDevPackagesByPackageNameResponses];

export type PutDevPackagesByPackageNameData = {
    body?: {
        description?: string;
        homepage_url?: string;
        requires_patching?: boolean;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}';
};

export type PutDevPackagesByPackageNameErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * System-managed packages cannot be updated
     */
    403: {
        success: false;
        code: 403;
        message: 'System-managed packages cannot be updated';
    };
    /**
     * Package with specified Name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified Name not found';
    };
};

export type PutDevPackagesByPackageNameError = PutDevPackagesByPackageNameErrors[keyof PutDevPackagesByPackageNameErrors];

export type PutDevPackagesByPackageNameResponses = {
    /**
     * Package updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package updated successfully';
        data: null;
    };
};

export type PutDevPackagesByPackageNameResponse = PutDevPackagesByPackageNameResponses[keyof PutDevPackagesByPackageNameResponses];

export type GetDevPackagesByPackageNameReleasesData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases';
};

export type GetDevPackagesByPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: Array<{
            id: number;
            versionWithLeiosPatch: string;
            architectures: {
                amd64: boolean;
                arm64: boolean;
                is_all: boolean;
            };
            created_at: number;
            changelog: string;
        }>;
    };
};

export type GetDevPackagesByPackageNameReleasesResponse = GetDevPackagesByPackageNameReleasesResponses[keyof GetDevPackagesByPackageNameReleasesResponses];

export type PostDevPackagesByPackageNameReleasesData = {
    body?: {
        versionWithLeiosPatch: string;
        changelog: string;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases';
};

export type PostDevPackagesByPackageNameReleasesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release with this version already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release with this version already exists';
    };
};

export type PostDevPackagesByPackageNameReleasesError = PostDevPackagesByPackageNameReleasesErrors[keyof PostDevPackagesByPackageNameReleasesErrors];

export type PostDevPackagesByPackageNameReleasesResponses = {
    /**
     * Package release created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release created successfully';
        data: null;
    };
};

export type PostDevPackagesByPackageNameReleasesResponse = PostDevPackagesByPackageNameReleasesResponses[keyof PostDevPackagesByPackageNameReleasesResponses];

export type GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchError = GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors[keyof GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors];

export type GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release retrieved successfully';
        data: {
            id: number;
            versionWithLeiosPatch: string;
            architectures: {
                amd64: boolean;
                arm64: boolean;
                is_all: boolean;
            };
            created_at: number;
            changelog: string;
        };
    };
};

export type GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses[keyof GetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses];

export type PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchData = {
    body?: {
        changelog?: string;
    };
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchError = PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors[keyof PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors];

export type PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release updated successfully';
        data: null;
    };
};

export type PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses[keyof PutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses];

export type PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchData = {
    body?: {
        file: Blob | File;
    };
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
        arch: 'amd64' | 'arm64' | 'all';
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{versionWithLeiosPatch}/{arch}';
};

export type PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release already contains a release for this architecture
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release already contains a release for this architecture';
    };
    /**
     * Failed to upload and verify package release asset
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to upload and verify package release asset';
    };
};

export type PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchError = PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchErrors[keyof PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchErrors];

export type PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponses = {
    /**
     * Package release file uploaded successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release file uploaded successfully';
        data: null;
    };
};

export type PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponse = PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponses[keyof PostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponses];

export type GetDevPackagesByPackageNameStablePromotionRequestsData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/dev/packages/{packageName}/stable-promotion-requests';
};

export type GetDevPackagesByPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        }>;
    };
};

export type GetDevPackagesByPackageNameStablePromotionRequestsResponse = GetDevPackagesByPackageNameStablePromotionRequestsResponses[keyof GetDevPackagesByPackageNameStablePromotionRequestsResponses];

export type PostDevPackagesByPackageNameStablePromotionRequestsData = {
    body?: {
        package_release_id: number;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/stable-promotion-requests';
};

export type PostDevPackagesByPackageNameStablePromotionRequestsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Release not found in archive repository
     */
    404: {
        success: false;
        code: 404;
        message: 'Release not found in archive repository';
    };
    /**
     * A request already for this release already exists or the release is already stable
     */
    409: {
        success: false;
        code: 409;
        message: 'A request already for this release already exists or the release is already stable';
    };
};

export type PostDevPackagesByPackageNameStablePromotionRequestsError = PostDevPackagesByPackageNameStablePromotionRequestsErrors[keyof PostDevPackagesByPackageNameStablePromotionRequestsErrors];

export type PostDevPackagesByPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion request submitted
     */
    201: {
        success: true;
        code: 201;
        message: 'Stable promotion request submitted';
        data: {
            id: number;
        };
    };
};

export type PostDevPackagesByPackageNameStablePromotionRequestsResponse = PostDevPackagesByPackageNameStablePromotionRequestsResponses[keyof PostDevPackagesByPackageNameStablePromotionRequestsResponses];

export type DeleteDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        packageName: string;
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/dev/packages/{packageName}/stable-promotion-requests/{stablePromotionRequestID}';
};

export type DeleteDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request deleted successfully';
        data: {
            [key: string]: unknown;
        };
    };
};

export type DeleteDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = DeleteDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses[keyof DeleteDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses];

export type GetDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        packageName: string;
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/dev/packages/{packageName}/stable-promotion-requests/{stablePromotionRequestID}';
};

export type GetDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request retrieved successfully';
        data: {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        };
    };
};

export type GetDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = GetDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses[keyof GetDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses];

export type GetDevTasksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/dev/tasks';
};

export type GetDevTasksResponses = {
    /**
     * Scheduled tasks retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'Scheduled tasks retrieved';
        data: Array<{
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        }>;
    };
};

export type GetDevTasksResponse = GetDevTasksResponses[keyof GetDevTasksResponses];

export type GetDevTasksByTaskIdData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/dev/tasks/{taskID}';
};

export type GetDevTasksByTaskIdErrors = {
    /**
     * Task with specified ID or Tag not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found';
    };
};

export type GetDevTasksByTaskIdError = GetDevTasksByTaskIdErrors[keyof GetDevTasksByTaskIdErrors];

export type GetDevTasksByTaskIdResponses = {
    /**
     * Task retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task retrieved successfully';
        data: {
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        };
    };
};

export type GetDevTasksByTaskIdResponse = GetDevTasksByTaskIdResponses[keyof GetDevTasksByTaskIdResponses];

export type GetDevTasksByTaskIdLogsData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/dev/tasks/{taskID}/logs';
};

export type GetDevTasksByTaskIdLogsErrors = {
    /**
     * Logs are not stored for this task
     */
    400: {
        success: false;
        code: 400;
        message: 'Logs are not stored for this task';
    };
    /**
     * Task with specified ID or Tag not found / Log file not found for this task
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found / Log file not found for this task';
    };
};

export type GetDevTasksByTaskIdLogsError = GetDevTasksByTaskIdLogsErrors[keyof GetDevTasksByTaskIdLogsErrors];

export type GetDevTasksByTaskIdLogsResponses = {
    /**
     * Task logs retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task logs retrieved successfully';
        data: {
            logs: string;
        };
    };
};

export type GetDevTasksByTaskIdLogsResponse = GetDevTasksByTaskIdLogsResponses[keyof GetDevTasksByTaskIdLogsResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'developer' | 'user';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body?: {
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'developer' | 'user';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersByUserIdErrors = {
    /**
     * Cannot delete user while packages are assigned
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete user while packages are assigned';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersByUserIdError = DeleteAdminUsersByUserIdErrors[keyof DeleteAdminUsersByUserIdErrors];

export type DeleteAdminUsersByUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersByUserIdResponse = DeleteAdminUsersByUserIdResponses[keyof DeleteAdminUsersByUserIdResponses];

export type GetAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersByUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersByUserIdError = GetAdminUsersByUserIdErrors[keyof GetAdminUsersByUserIdErrors];

export type GetAdminUsersByUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type GetAdminUsersByUserIdResponse = GetAdminUsersByUserIdResponses[keyof GetAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'developer' | 'user';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersByUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersByUserIdError = PutAdminUsersByUserIdErrors[keyof PutAdminUsersByUserIdErrors];

export type PutAdminUsersByUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type PutAdminUsersByUserIdResponse = PutAdminUsersByUserIdResponses[keyof PutAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdPasswordData = {
    body?: {
        /**
         * New password for the account
         */
        password: string;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersByUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersByUserIdPasswordError = PutAdminUsersByUserIdPasswordErrors[keyof PutAdminUsersByUserIdPasswordErrors];

export type PutAdminUsersByUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersByUserIdPasswordResponse = PutAdminUsersByUserIdPasswordResponses[keyof PutAdminUsersByUserIdPasswordResponses];

export type GetAdminPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/packages';
};

export type GetAdminPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            owner_user_id: number;
            flags: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release: {
                amd64: string | null;
                arm64: string | null;
            };
            latest_testing_release: {
                amd64: string | null;
                arm64: string | null;
            };
        }>;
    };
};

export type GetAdminPackagesResponse = GetAdminPackagesResponses[keyof GetAdminPackagesResponses];

export type PostAdminPackagesData = {
    body?: {
        name: string;
        owner_user_id: number;
        description: string;
        homepage_url: string;
        requires_patching?: boolean;
    };
    path?: never;
    query?: never;
    url: '/admin/packages';
};

export type PostAdminPackagesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package with this name already exists';
    };
};

export type PostAdminPackagesError = PostAdminPackagesErrors[keyof PostAdminPackagesErrors];

export type PostAdminPackagesResponses = {
    /**
     * Package created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package created successfully';
        data: null;
    };
};

export type PostAdminPackagesResponse = PostAdminPackagesResponses[keyof PostAdminPackagesResponses];

export type DeleteAdminPackagesByPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}';
};

export type DeleteAdminPackagesByPackageNameErrors = {
    /**
     * System-managed packages cannot be updated
     */
    403: {
        success: false;
        code: 403;
        message: 'System-managed packages cannot be updated';
    };
    /**
     * Package with specified Name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified Name not found';
    };
};

export type DeleteAdminPackagesByPackageNameError = DeleteAdminPackagesByPackageNameErrors[keyof DeleteAdminPackagesByPackageNameErrors];

export type DeleteAdminPackagesByPackageNameResponses = {
    /**
     * Package deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package deleted successfully';
        data: null;
    };
};

export type DeleteAdminPackagesByPackageNameResponse = DeleteAdminPackagesByPackageNameResponses[keyof DeleteAdminPackagesByPackageNameResponses];

export type GetAdminPackagesByPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}';
};

export type GetAdminPackagesByPackageNameErrors = {
    /**
     * Package with specified Name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified Name not found';
    };
};

export type GetAdminPackagesByPackageNameError = GetAdminPackagesByPackageNameErrors[keyof GetAdminPackagesByPackageNameErrors];

export type GetAdminPackagesByPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            id: number;
            name: string;
            owner_user_id: number;
            flags: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release: {
                amd64: string | null;
                arm64: string | null;
            };
            latest_testing_release: {
                amd64: string | null;
                arm64: string | null;
            };
        };
    };
};

export type GetAdminPackagesByPackageNameResponse = GetAdminPackagesByPackageNameResponses[keyof GetAdminPackagesByPackageNameResponses];

export type PutAdminPackagesByPackageNameData = {
    body?: {
        description?: string;
        homepage_url?: string;
        requires_patching?: boolean;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}';
};

export type PutAdminPackagesByPackageNameErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * System-managed packages cannot be updated
     */
    403: {
        success: false;
        code: 403;
        message: 'System-managed packages cannot be updated';
    };
    /**
     * Package with specified Name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified Name not found';
    };
};

export type PutAdminPackagesByPackageNameError = PutAdminPackagesByPackageNameErrors[keyof PutAdminPackagesByPackageNameErrors];

export type PutAdminPackagesByPackageNameResponses = {
    /**
     * Package updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package updated successfully';
        data: null;
    };
};

export type PutAdminPackagesByPackageNameResponse = PutAdminPackagesByPackageNameResponses[keyof PutAdminPackagesByPackageNameResponses];

export type GetAdminPackagesByPackageNameReleasesData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases';
};

export type GetAdminPackagesByPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: Array<{
            id: number;
            versionWithLeiosPatch: string;
            architectures: {
                amd64: boolean;
                arm64: boolean;
                is_all: boolean;
            };
            created_at: number;
            changelog: string;
        }>;
    };
};

export type GetAdminPackagesByPackageNameReleasesResponse = GetAdminPackagesByPackageNameReleasesResponses[keyof GetAdminPackagesByPackageNameReleasesResponses];

export type PostAdminPackagesByPackageNameReleasesData = {
    body?: {
        versionWithLeiosPatch: string;
        changelog: string;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases';
};

export type PostAdminPackagesByPackageNameReleasesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release with this version already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release with this version already exists';
    };
};

export type PostAdminPackagesByPackageNameReleasesError = PostAdminPackagesByPackageNameReleasesErrors[keyof PostAdminPackagesByPackageNameReleasesErrors];

export type PostAdminPackagesByPackageNameReleasesResponses = {
    /**
     * Package release created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release created successfully';
        data: null;
    };
};

export type PostAdminPackagesByPackageNameReleasesResponse = PostAdminPackagesByPackageNameReleasesResponses[keyof PostAdminPackagesByPackageNameReleasesResponses];

export type DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * Package release with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified ID not found';
    };
};

export type DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchError = DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors[keyof DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors];

export type DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release deleted successfully';
        data: null;
    };
};

export type DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses[keyof DeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses];

export type GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchError = GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors[keyof GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors];

export type GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release retrieved successfully';
        data: {
            id: number;
            versionWithLeiosPatch: string;
            architectures: {
                amd64: boolean;
                arm64: boolean;
                is_all: boolean;
            };
            created_at: number;
            changelog: string;
        };
    };
};

export type GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses[keyof GetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses];

export type PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchData = {
    body?: {
        changelog?: string;
    };
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchError = PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors[keyof PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchErrors];

export type PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release updated successfully';
        data: null;
    };
};

export type PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses[keyof PutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponses];

export type PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchData = {
    body?: {
        file: Blob | File;
    };
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
        arch: 'amd64' | 'arm64' | 'all';
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}/{arch}';
};

export type PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release already contains a release for this architecture
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release already contains a release for this architecture';
    };
    /**
     * Failed to upload and verify package release asset
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to upload and verify package release asset';
    };
};

export type PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchError = PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchErrors[keyof PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchErrors];

export type PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponses = {
    /**
     * Package release file uploaded successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release file uploaded successfully';
        data: null;
    };
};

export type PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponse = PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponses[keyof PostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponses];

export type GetAdminPackagesByPackageNameStablePromotionRequestsData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/admin/packages/{packageName}/stable-promotion-requests';
};

export type GetAdminPackagesByPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        }>;
    };
};

export type GetAdminPackagesByPackageNameStablePromotionRequestsResponse = GetAdminPackagesByPackageNameStablePromotionRequestsResponses[keyof GetAdminPackagesByPackageNameStablePromotionRequestsResponses];

export type PostAdminPackagesByPackageNameStablePromotionRequestsData = {
    body?: {
        package_release_id: number;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/stable-promotion-requests';
};

export type PostAdminPackagesByPackageNameStablePromotionRequestsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Release not found in archive repository
     */
    404: {
        success: false;
        code: 404;
        message: 'Release not found in archive repository';
    };
    /**
     * A request already for this release already exists or the release is already stable
     */
    409: {
        success: false;
        code: 409;
        message: 'A request already for this release already exists or the release is already stable';
    };
};

export type PostAdminPackagesByPackageNameStablePromotionRequestsError = PostAdminPackagesByPackageNameStablePromotionRequestsErrors[keyof PostAdminPackagesByPackageNameStablePromotionRequestsErrors];

export type PostAdminPackagesByPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion request submitted
     */
    201: {
        success: true;
        code: 201;
        message: 'Stable promotion request submitted';
        data: {
            id: number;
        };
    };
};

export type PostAdminPackagesByPackageNameStablePromotionRequestsResponse = PostAdminPackagesByPackageNameStablePromotionRequestsResponses[keyof PostAdminPackagesByPackageNameStablePromotionRequestsResponses];

export type DeleteAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        packageName: string;
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/admin/packages/{packageName}/stable-promotion-requests/{stablePromotionRequestID}';
};

export type DeleteAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request deleted successfully';
        data: {
            [key: string]: unknown;
        };
    };
};

export type DeleteAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = DeleteAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses[keyof DeleteAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses];

export type GetAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        packageName: string;
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/admin/packages/{packageName}/stable-promotion-requests/{stablePromotionRequestID}';
};

export type GetAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request retrieved successfully';
        data: {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        };
    };
};

export type GetAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = GetAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses[keyof GetAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses];

export type GetAdminOsReleasesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
    };
    url: '/admin/os-releases';
};

export type GetAdminOsReleasesResponses = {
    /**
     * OS releases retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'OS releases retrieved';
        data: Array<{
            id: number;
            version: string;
            changelog: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        }>;
    };
};

export type GetAdminOsReleasesResponse = GetAdminOsReleasesResponses[keyof GetAdminOsReleasesResponses];

export type PostAdminOsReleasesData = {
    body?: {
        changelog: string;
    };
    path?: never;
    query?: never;
    url: '/admin/os-releases';
};

export type PostAdminOsReleasesResponses = {
    /**
     * OS release creation task enqueued
     */
    202: {
        success: true;
        code: 202;
        message: 'OS release creation task enqueued';
        data: {
            id: number;
            version: string;
            changelog: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        };
    };
};

export type PostAdminOsReleasesResponse = PostAdminOsReleasesResponses[keyof PostAdminOsReleasesResponses];

export type GetAdminOsReleasesByVersionData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/admin/os-releases/{version}';
};

export type GetAdminOsReleasesByVersionErrors = {
    /**
     * OS release not found
     */
    404: {
        success: false;
        code: 404;
        message: 'OS release not found';
    };
};

export type GetAdminOsReleasesByVersionError = GetAdminOsReleasesByVersionErrors[keyof GetAdminOsReleasesByVersionErrors];

export type GetAdminOsReleasesByVersionResponses = {
    /**
     * OS release retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'OS release retrieved';
        data: {
            id: number;
            version: string;
            changelog: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        };
    };
};

export type GetAdminOsReleasesByVersionResponse = GetAdminOsReleasesByVersionResponses[keyof GetAdminOsReleasesByVersionResponses];

export type PutAdminOsReleasesByVersionData = {
    body?: {
        changelog?: string;
    };
    path: {
        version: string;
    };
    query?: never;
    url: '/admin/os-releases/{version}';
};

export type PutAdminOsReleasesByVersionErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * OS release not found
     */
    404: {
        success: false;
        code: 404;
        message: 'OS release not found';
    };
};

export type PutAdminOsReleasesByVersionError = PutAdminOsReleasesByVersionErrors[keyof PutAdminOsReleasesByVersionErrors];

export type PutAdminOsReleasesByVersionResponses = {
    /**
     * OS release updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'OS release updated successfully';
        data: null;
    };
};

export type PutAdminOsReleasesByVersionResponse = PutAdminOsReleasesByVersionResponses[keyof PutAdminOsReleasesByVersionResponses];

export type GetAdminOsReleasesByVersionPublishingLogsData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/admin/os-releases/{version}/publishing-logs';
};

export type GetAdminOsReleasesByVersionPublishingLogsErrors = {
    /**
     * OS release not found / Log file not found for this OS release publishing task
     */
    404: {
        success: false;
        code: 404;
        message: 'OS release not found / Log file not found for this OS release publishing task';
    };
};

export type GetAdminOsReleasesByVersionPublishingLogsError = GetAdminOsReleasesByVersionPublishingLogsErrors[keyof GetAdminOsReleasesByVersionPublishingLogsErrors];

export type GetAdminOsReleasesByVersionPublishingLogsResponses = {
    /**
     * Publishing logs retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'Publishing logs retrieved';
        data: {
            logs: string;
        };
    };
};

export type GetAdminOsReleasesByVersionPublishingLogsResponse = GetAdminOsReleasesByVersionPublishingLogsResponses[keyof GetAdminOsReleasesByVersionPublishingLogsResponses];

export type GetAdminStablePromotionRequestsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
    };
    url: '/admin/stable-promotion-requests';
};

export type GetAdminStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending' | 'approved' | 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        }>;
    };
};

export type GetAdminStablePromotionRequestsResponse = GetAdminStablePromotionRequestsResponses[keyof GetAdminStablePromotionRequestsResponses];

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/admin/stable-promotion-requests/{stablePromotionRequestID}';
};

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdErrors = {
    /**
     * Stable promotion request not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Stable promotion request not found';
    };
};

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdError = GetAdminStablePromotionRequestsByStablePromotionRequestIdErrors[keyof GetAdminStablePromotionRequestsByStablePromotionRequestIdErrors];

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request retrieved successfully';
        data: {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending' | 'approved' | 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        };
    };
};

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdResponse = GetAdminStablePromotionRequestsByStablePromotionRequestIdResponses[keyof GetAdminStablePromotionRequestsByStablePromotionRequestIdResponses];

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideData = {
    body?: {
        status: 'approved' | 'denied';
        admin_note: string;
    };
    path: {
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/admin/stable-promotion-requests/{stablePromotionRequestID}/decide';
};

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Stable promotion request not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Stable promotion request not found';
    };
};

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideError = PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideErrors[keyof PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideErrors];

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponses = {
    /**
     * Decided on stable promotion request successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Decided on stable promotion request successfully';
        data: null;
    };
};

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponse = PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponses[keyof PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponses];

export type GetAdminTasksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/admin/tasks';
};

export type GetAdminTasksResponses = {
    /**
     * Scheduled tasks retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'Scheduled tasks retrieved';
        data: Array<{
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        }>;
    };
};

export type GetAdminTasksResponse = GetAdminTasksResponses[keyof GetAdminTasksResponses];

export type GetAdminTasksByTaskIdData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/admin/tasks/{taskID}';
};

export type GetAdminTasksByTaskIdErrors = {
    /**
     * Task with specified ID or Tag not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found';
    };
};

export type GetAdminTasksByTaskIdError = GetAdminTasksByTaskIdErrors[keyof GetAdminTasksByTaskIdErrors];

export type GetAdminTasksByTaskIdResponses = {
    /**
     * Task retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task retrieved successfully';
        data: {
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        };
    };
};

export type GetAdminTasksByTaskIdResponse = GetAdminTasksByTaskIdResponses[keyof GetAdminTasksByTaskIdResponses];

export type GetAdminTasksByTaskIdLogsData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/admin/tasks/{taskID}/logs';
};

export type GetAdminTasksByTaskIdLogsErrors = {
    /**
     * Logs are not stored for this task
     */
    400: {
        success: false;
        code: 400;
        message: 'Logs are not stored for this task';
    };
    /**
     * Task with specified ID or Tag not found / Log file not found for this task
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found / Log file not found for this task';
    };
};

export type GetAdminTasksByTaskIdLogsError = GetAdminTasksByTaskIdLogsErrors[keyof GetAdminTasksByTaskIdLogsErrors];

export type GetAdminTasksByTaskIdLogsResponses = {
    /**
     * Task logs retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task logs retrieved successfully';
        data: {
            logs: string;
        };
    };
};

export type GetAdminTasksByTaskIdLogsResponse = GetAdminTasksByTaskIdLogsResponses[keyof GetAdminTasksByTaskIdLogsResponses];
