// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:12151/v1/' | 'https://api.leios.dev/v1/' | (string & {});
};

export type PostAuthLoginData = {
    body: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Invalid username or password / You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'Invalid username or password / You are already authenticated';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'You are already authenticated';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type PostAuthResetPasswordRequestData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password/request';
};

export type PostAuthResetPasswordRequestErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'You are already authenticated';
    };
};

export type PostAuthResetPasswordRequestError = PostAuthResetPasswordRequestErrors[keyof PostAuthResetPasswordRequestErrors];

export type PostAuthResetPasswordRequestResponses = {
    /**
     * If the username exists, a password reset has been requested
     */
    200: {
        success: true;
        code: 200;
        message: 'If the username exists, a password reset has been requested';
        data: null;
    };
};

export type PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponses[keyof PostAuthResetPasswordRequestResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body: {
        username?: string;
        display_name?: string;
        email?: string;
    } & {
        /**
         * Current password — required to confirm account changes
         */
        current_password: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAccountApikeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type GetAccountApikeysResponses = {
    /**
     * API keys retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API keys retrieved successfully';
        data: Array<{
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        }>;
    };
};

export type GetAccountApikeysResponse = GetAccountApikeysResponses[keyof GetAccountApikeysResponses];

export type PostAccountApikeysData = {
    body: {
        description: string;
        expires_at: '7d' | '30d' | '90d' | '180d' | '365d' | null;
    };
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type PostAccountApikeysErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAccountApikeysError = PostAccountApikeysErrors[keyof PostAccountApikeysErrors];

export type PostAccountApikeysResponses = {
    /**
     * API key created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key created successfully';
        data: {
            id: string;
            token: string;
        };
    };
};

export type PostAccountApikeysResponse = PostAccountApikeysResponses[keyof PostAccountApikeysResponses];

export type DeleteAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type DeleteAccountApikeysByApiKeyIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type DeleteAccountApikeysByApiKeyIdError = DeleteAccountApikeysByApiKeyIdErrors[keyof DeleteAccountApikeysByApiKeyIdErrors];

export type DeleteAccountApikeysByApiKeyIdResponses = {
    /**
     * API key deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key deleted successfully';
        data: null;
    };
};

export type DeleteAccountApikeysByApiKeyIdResponse = DeleteAccountApikeysByApiKeyIdResponses[keyof DeleteAccountApikeysByApiKeyIdResponses];

export type GetAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type GetAccountApikeysByApiKeyIdErrors = {
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type GetAccountApikeysByApiKeyIdError = GetAccountApikeysByApiKeyIdErrors[keyof GetAccountApikeysByApiKeyIdErrors];

export type GetAccountApikeysByApiKeyIdResponses = {
    /**
     * API key retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key retrieved successfully';
        data: {
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        };
    };
};

export type GetAccountApikeysByApiKeyIdResponse = GetAccountApikeysByApiKeyIdResponses[keyof GetAccountApikeysByApiKeyIdResponses];

export type GetPublishersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        searchString?: string;
        onlyMembershipByMe?: boolean;
    };
    url: '/publishers';
};

export type GetPublishersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type GetPublishersError = GetPublishersErrors[keyof GetPublishersErrors];

export type GetPublishersResponses = {
    /**
     * Publishers retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Publishers retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            display_name: string;
            description: string;
            homepage_url: string;
            created_at: number;
        }>;
    };
};

export type GetPublishersResponse = GetPublishersResponses[keyof GetPublishersResponses];

export type PostPublishersData = {
    body: {
        name: string;
        display_name: string;
        description: string;
        homepage_url: string;
    };
    path?: never;
    query?: never;
    url: '/publishers';
};

export type PostPublishersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Publisher with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Publisher with this name already exists';
    };
};

export type PostPublishersError = PostPublishersErrors[keyof PostPublishersErrors];

export type PostPublishersResponses = {
    /**
     * Publisher created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Publisher created successfully';
        data: {
            id: number;
        };
    };
};

export type PostPublishersResponse = PostPublishersResponses[keyof PostPublishersResponses];

export type DeletePublishersByPublisherNameData = {
    body?: never;
    path: {
        publisherName: string;
    };
    query?: never;
    url: '/publishers/{publisherName}';
};

export type DeletePublishersByPublisherNameErrors = {
    /**
     * Cannot delete publisher with existing packages
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete publisher with existing packages';
    };
    /**
     * Only the publisher owner can delete this publisher
     */
    403: {
        success: false;
        code: 403;
        message: 'Only the publisher owner can delete this publisher';
    };
    /**
     * Publisher not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Publisher not found';
    };
};

export type DeletePublishersByPublisherNameError = DeletePublishersByPublisherNameErrors[keyof DeletePublishersByPublisherNameErrors];

export type DeletePublishersByPublisherNameResponses = {
    /**
     * Publisher deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Publisher deleted successfully';
        data: null;
    };
};

export type DeletePublishersByPublisherNameResponse = DeletePublishersByPublisherNameResponses[keyof DeletePublishersByPublisherNameResponses];

export type GetPublishersByPublisherNameData = {
    body?: never;
    path: {
        publisherName: string;
    };
    query?: never;
    url: '/publishers/{publisherName}';
};

export type GetPublishersByPublisherNameErrors = {
    /**
     * Publisher not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Publisher not found';
    };
};

export type GetPublishersByPublisherNameError = GetPublishersByPublisherNameErrors[keyof GetPublishersByPublisherNameErrors];

export type GetPublishersByPublisherNameResponses = {
    /**
     * Publisher retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Publisher retrieved successfully';
        data: {
            id: number;
            name: string;
            display_name: string;
            description: string;
            homepage_url: string;
            created_at: number;
        };
    };
};

export type GetPublishersByPublisherNameResponse = GetPublishersByPublisherNameResponses[keyof GetPublishersByPublisherNameResponses];

export type PutPublishersByPublisherNameData = {
    body: {
        display_name?: string;
        description?: string;
        homepage_url?: string;
    };
    path: {
        publisherName: string;
    };
    query?: never;
    url: '/publishers/{publisherName}';
};

export type PutPublishersByPublisherNameErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to update this publisher
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to update this publisher';
    };
    /**
     * Publisher not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Publisher not found';
    };
};

export type PutPublishersByPublisherNameError = PutPublishersByPublisherNameErrors[keyof PutPublishersByPublisherNameErrors];

export type PutPublishersByPublisherNameResponses = {
    /**
     * Publisher updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Publisher updated successfully';
        data: null;
    };
};

export type PutPublishersByPublisherNameResponse = PutPublishersByPublisherNameResponses[keyof PutPublishersByPublisherNameResponses];

export type PostPublishersByPublisherNameTransferOwnershipData = {
    body: {
        new_owner_user_id: number;
    };
    path: {
        publisherName: string;
    };
    query?: never;
    url: '/publishers/{publisherName}/transfer-ownership';
};

export type PostPublishersByPublisherNameTransferOwnershipErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Only the current owner can transfer ownership
     */
    403: {
        success: false;
        code: 403;
        message: 'Only the current owner can transfer ownership';
    };
    /**
     * Publisher not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Publisher not found';
    };
};

export type PostPublishersByPublisherNameTransferOwnershipError = PostPublishersByPublisherNameTransferOwnershipErrors[keyof PostPublishersByPublisherNameTransferOwnershipErrors];

export type PostPublishersByPublisherNameTransferOwnershipResponses = {
    /**
     * Publisher ownership transferred successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Publisher ownership transferred successfully';
        data: null;
    };
};

export type PostPublishersByPublisherNameTransferOwnershipResponse = PostPublishersByPublisherNameTransferOwnershipResponses[keyof PostPublishersByPublisherNameTransferOwnershipResponses];

export type GetPublishersByPublisherNameMembersData = {
    body?: never;
    path: {
        publisherName: string;
    };
    query?: never;
    url: '/publishers/{publisherName}/members';
};

export type GetPublishersByPublisherNameMembersResponses = {
    /**
     * Members retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Members retrieved successfully';
        data: Array<{
            id: number;
            user_id: number;
            role: 'ADMIN' | 'MAINTAINER' | 'DEVELOPER' | 'VIEWER';
            is_publicly_hidden: boolean;
            added_at: number;
            user_username: string;
            user_display_name: string;
        }>;
    };
};

export type GetPublishersByPublisherNameMembersResponse = GetPublishersByPublisherNameMembersResponses[keyof GetPublishersByPublisherNameMembersResponses];

export type PostPublishersByPublisherNameMembersData = {
    body: {
        user_id: number;
        role: 'ADMIN' | 'MAINTAINER' | 'DEVELOPER' | 'VIEWER';
        is_publicly_hidden?: boolean;
    };
    path: {
        publisherName: string;
    };
    query?: never;
    url: '/publishers/{publisherName}/members';
};

export type PostPublishersByPublisherNameMembersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to manage members
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to manage members';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * User is already a member
     */
    409: {
        success: false;
        code: 409;
        message: 'User is already a member';
    };
};

export type PostPublishersByPublisherNameMembersError = PostPublishersByPublisherNameMembersErrors[keyof PostPublishersByPublisherNameMembersErrors];

export type PostPublishersByPublisherNameMembersResponses = {
    /**
     * Member added successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Member added successfully';
        data: {
            id: number;
        };
    };
};

export type PostPublishersByPublisherNameMembersResponse = PostPublishersByPublisherNameMembersResponses[keyof PostPublishersByPublisherNameMembersResponses];

export type DeletePublishersByPublisherNameMembersByUserIdData = {
    body?: never;
    path: {
        publisherName: string;
        userId: number;
    };
    query?: never;
    url: '/publishers/{publisherName}/members/{userId}';
};

export type DeletePublishersByPublisherNameMembersByUserIdErrors = {
    /**
     * Cannot remove the publisher owner
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot remove the publisher owner';
    };
    /**
     * You do not have permission to manage members
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to manage members';
    };
    /**
     * Member not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Member not found';
    };
};

export type DeletePublishersByPublisherNameMembersByUserIdError = DeletePublishersByPublisherNameMembersByUserIdErrors[keyof DeletePublishersByPublisherNameMembersByUserIdErrors];

export type DeletePublishersByPublisherNameMembersByUserIdResponses = {
    /**
     * Member removed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Member removed successfully';
        data: null;
    };
};

export type DeletePublishersByPublisherNameMembersByUserIdResponse = DeletePublishersByPublisherNameMembersByUserIdResponses[keyof DeletePublishersByPublisherNameMembersByUserIdResponses];

export type GetPublishersByPublisherNameMembersByUserIdData = {
    body?: never;
    path: {
        publisherName: string;
        userId: number;
    };
    query?: never;
    url: '/publishers/{publisherName}/members/{userId}';
};

export type GetPublishersByPublisherNameMembersByUserIdErrors = {
    /**
     * Member not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Member not found';
    };
};

export type GetPublishersByPublisherNameMembersByUserIdError = GetPublishersByPublisherNameMembersByUserIdErrors[keyof GetPublishersByPublisherNameMembersByUserIdErrors];

export type GetPublishersByPublisherNameMembersByUserIdResponses = {
    /**
     * Member retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Member retrieved successfully';
        data: {
            id: number;
            user_id: number;
            role: 'ADMIN' | 'MAINTAINER' | 'DEVELOPER' | 'VIEWER';
            is_publicly_hidden: boolean;
            added_at: number;
            user_username: string;
            user_display_name: string;
        };
    };
};

export type GetPublishersByPublisherNameMembersByUserIdResponse = GetPublishersByPublisherNameMembersByUserIdResponses[keyof GetPublishersByPublisherNameMembersByUserIdResponses];

export type PutPublishersByPublisherNameMembersByUserIdData = {
    body: {
        role?: 'ADMIN' | 'MAINTAINER' | 'DEVELOPER' | 'VIEWER';
        is_publicly_hidden?: boolean;
    };
    path: {
        publisherName: string;
        userId: number;
    };
    query?: never;
    url: '/publishers/{publisherName}/members/{userId}';
};

export type PutPublishersByPublisherNameMembersByUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to manage members
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to manage members';
    };
    /**
     * Member not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Member not found';
    };
};

export type PutPublishersByPublisherNameMembersByUserIdError = PutPublishersByPublisherNameMembersByUserIdErrors[keyof PutPublishersByPublisherNameMembersByUserIdErrors];

export type PutPublishersByPublisherNameMembersByUserIdResponses = {
    /**
     * Member updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Member updated successfully';
        data: null;
    };
};

export type PutPublishersByPublisherNameMembersByUserIdResponse = PutPublishersByPublisherNameMembersByUserIdResponses[keyof PutPublishersByPublisherNameMembersByUserIdResponses];

export type GetPackagesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        searchString?: string;
        publisherID?: number;
        publisherName?: string;
        onlyMembershipByMe?: boolean;
    };
    url: '/packages';
};

export type GetPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            id: number;
            publisher_id: number;
            name: string;
            fullname: string;
            top_level_alias: string | null;
            display_name: string;
            description: string;
            homepage_url: string;
            flags: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release: {
                amd64: string | null;
                arm64: string | null;
            };
            latest_testing_release: {
                amd64: string | null;
                arm64: string | null;
            };
        }>;
    };
};

export type GetPackagesResponse = GetPackagesResponses[keyof GetPackagesResponses];

export type PostPackagesData = {
    body: {
        publisher_id: number;
        name: string;
        display_name: string;
        description: string;
        homepage_url: string;
        requires_patching?: boolean;
    };
    path?: never;
    query?: never;
    url: '/packages';
};

export type PostPackagesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to create packages in this publisher
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to create packages in this publisher';
    };
    /**
     * Publisher not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Publisher not found';
    };
    /**
     * Package with this name already exists in this publisher
     */
    409: {
        success: false;
        code: 409;
        message: 'Package with this name already exists in this publisher';
    };
};

export type PostPackagesError = PostPackagesErrors[keyof PostPackagesErrors];

export type PostPackagesResponses = {
    /**
     * Package created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package created successfully';
        data: null;
    };
};

export type PostPackagesResponse = PostPackagesResponses[keyof PostPackagesResponses];

export type DeletePackagesByFullPackageNameData = {
    body?: never;
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}';
};

export type DeletePackagesByFullPackageNameErrors = {
    /**
     * System-managed packages cannot be deleted / You do not have permission to delete this package
     */
    403: {
        success: false;
        code: 403;
        message: 'System-managed packages cannot be deleted / You do not have permission to delete this package';
    };
    /**
     * Package with specified name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified name not found';
    };
    /**
     * Failed to delete package from Aptly repositories
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to delete package from Aptly repositories';
    };
};

export type DeletePackagesByFullPackageNameError = DeletePackagesByFullPackageNameErrors[keyof DeletePackagesByFullPackageNameErrors];

export type DeletePackagesByFullPackageNameResponses = {
    /**
     * Package deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package deleted successfully';
        data: null;
    };
};

export type DeletePackagesByFullPackageNameResponse = DeletePackagesByFullPackageNameResponses[keyof DeletePackagesByFullPackageNameResponses];

export type GetPackagesByFullPackageNameData = {
    body?: never;
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}';
};

export type GetPackagesByFullPackageNameErrors = {
    /**
     * Package with specified name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified name not found';
    };
};

export type GetPackagesByFullPackageNameError = GetPackagesByFullPackageNameErrors[keyof GetPackagesByFullPackageNameErrors];

export type GetPackagesByFullPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            id: number;
            publisher_id: number;
            name: string;
            fullname: string;
            top_level_alias: string | null;
            display_name: string;
            description: string;
            homepage_url: string;
            flags: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release: {
                amd64: string | null;
                arm64: string | null;
            };
            latest_testing_release: {
                amd64: string | null;
                arm64: string | null;
            };
        };
    };
};

export type GetPackagesByFullPackageNameResponse = GetPackagesByFullPackageNameResponses[keyof GetPackagesByFullPackageNameResponses];

export type PutPackagesByFullPackageNameData = {
    body: {
        display_name?: string;
        description?: string;
        homepage_url?: string;
        requires_patching?: boolean;
    };
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}';
};

export type PutPackagesByFullPackageNameErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * System-managed packages cannot be updated / You do not have permission to update this package
     */
    403: {
        success: false;
        code: 403;
        message: 'System-managed packages cannot be updated / You do not have permission to update this package';
    };
    /**
     * Package with specified name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified name not found';
    };
};

export type PutPackagesByFullPackageNameError = PutPackagesByFullPackageNameErrors[keyof PutPackagesByFullPackageNameErrors];

export type PutPackagesByFullPackageNameResponses = {
    /**
     * Package updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package updated successfully';
        data: null;
    };
};

export type PutPackagesByFullPackageNameResponse = PutPackagesByFullPackageNameResponses[keyof PutPackagesByFullPackageNameResponses];

export type GetPackagesByFullPackageNameReleasesData = {
    body?: never;
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/releases';
};

export type GetPackagesByFullPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: Array<{
            id: number;
            version_with_leios_patch: string;
            architectures: {
                amd64: boolean;
                arm64: boolean;
                is_all: boolean;
            };
            created_at: number;
            changelog: string;
        }>;
    };
};

export type GetPackagesByFullPackageNameReleasesResponse = GetPackagesByFullPackageNameReleasesResponses[keyof GetPackagesByFullPackageNameReleasesResponses];

export type PostPackagesByFullPackageNameReleasesData = {
    body: {
        version_with_leios_patch: string;
        changelog: string;
    };
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/releases';
};

export type PostPackagesByFullPackageNameReleasesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to publish releases for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to publish releases for this package';
    };
    /**
     * Package release with this version already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release with this version already exists';
    };
};

export type PostPackagesByFullPackageNameReleasesError = PostPackagesByFullPackageNameReleasesErrors[keyof PostPackagesByFullPackageNameReleasesErrors];

export type PostPackagesByFullPackageNameReleasesResponses = {
    /**
     * Package release created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release created successfully';
        data: null;
    };
};

export type PostPackagesByFullPackageNameReleasesResponse = PostPackagesByFullPackageNameReleasesResponses[keyof PostPackagesByFullPackageNameReleasesResponses];

export type DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchData = {
    body?: never;
    path: {
        fullPackageName: string;
        version_with_leios_patch: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/releases/{version_with_leios_patch}';
};

export type DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * You do not have permission to delete releases for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to delete releases for this package';
    };
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
    /**
     * Failed to delete release from Aptly repositories
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to delete release from Aptly repositories';
    };
};

export type DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchError = DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors[keyof DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors];

export type DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release deleted successfully';
        data: null;
    };
};

export type DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponse = DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses[keyof DeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses];

export type GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchData = {
    body?: never;
    path: {
        fullPackageName: string;
        version_with_leios_patch: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/releases/{version_with_leios_patch}';
};

export type GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchError = GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors[keyof GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors];

export type GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release retrieved successfully';
        data: {
            id: number;
            version_with_leios_patch: string;
            architectures: {
                amd64: boolean;
                arm64: boolean;
                is_all: boolean;
            };
            created_at: number;
            changelog: string;
        };
    };
};

export type GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponse = GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses[keyof GetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses];

export type PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchData = {
    body: {
        changelog?: string;
    };
    path: {
        fullPackageName: string;
        version_with_leios_patch: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/releases/{version_with_leios_patch}';
};

export type PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to update releases for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to update releases for this package';
    };
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchError = PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors[keyof PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchErrors];

export type PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses = {
    /**
     * Package release updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release updated successfully';
        data: null;
    };
};

export type PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponse = PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses[keyof PutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponses];

export type PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchData = {
    body: {
        file: Blob | File;
    };
    path: {
        fullPackageName: string;
        version_with_leios_patch: string;
        arch: 'amd64' | 'arm64' | 'all';
    };
    query?: never;
    url: '/packages/{fullPackageName}/releases/{version_with_leios_patch}/{arch}';
};

export type PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to publish releases for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to publish releases for this package';
    };
    /**
     * Package release already contains a release for this architecture
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release already contains a release for this architecture';
    };
    /**
     * Failed to upload and verify package release asset
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to upload and verify package release asset';
    };
};

export type PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchError = PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchErrors[keyof PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchErrors];

export type PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchResponses = {
    /**
     * Package release file uploaded successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release file uploaded successfully';
        data: null;
    };
};

export type PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchResponse = PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchResponses[keyof PostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchResponses];

export type GetPackagesByFullPackageNameStablePromotionRequestsData = {
    body?: never;
    path: {
        fullPackageName: string;
    };
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/packages/{fullPackageName}/stable-promotion-requests';
};

export type GetPackagesByFullPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        }>;
    };
};

export type GetPackagesByFullPackageNameStablePromotionRequestsResponse = GetPackagesByFullPackageNameStablePromotionRequestsResponses[keyof GetPackagesByFullPackageNameStablePromotionRequestsResponses];

export type PostPackagesByFullPackageNameStablePromotionRequestsData = {
    body: {
        package_release_id: number;
    };
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/stable-promotion-requests';
};

export type PostPackagesByFullPackageNameStablePromotionRequestsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to request stable promotions for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to request stable promotions for this package';
    };
    /**
     * Release not found in archive repository
     */
    404: {
        success: false;
        code: 404;
        message: 'Release not found in archive repository';
    };
    /**
     * A request already for this release already exists or the release is already stable
     */
    409: {
        success: false;
        code: 409;
        message: 'A request already for this release already exists or the release is already stable';
    };
};

export type PostPackagesByFullPackageNameStablePromotionRequestsError = PostPackagesByFullPackageNameStablePromotionRequestsErrors[keyof PostPackagesByFullPackageNameStablePromotionRequestsErrors];

export type PostPackagesByFullPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion request submitted
     */
    201: {
        success: true;
        code: 201;
        message: 'Stable promotion request submitted';
        data: {
            id: number;
        };
    };
};

export type PostPackagesByFullPackageNameStablePromotionRequestsResponse = PostPackagesByFullPackageNameStablePromotionRequestsResponses[keyof PostPackagesByFullPackageNameStablePromotionRequestsResponses];

export type DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        fullPackageName: string;
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/packages/{fullPackageName}/stable-promotion-requests/{stablePromotionRequestID}';
};

export type DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdErrors = {
    /**
     * You do not have permission to delete stable promotion requests for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to delete stable promotion requests for this package';
    };
};

export type DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdError = DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdErrors[keyof DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdErrors];

export type DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request deleted successfully';
        data: null;
    };
};

export type DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses[keyof DeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses];

export type GetPackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        fullPackageName: string;
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/packages/{fullPackageName}/stable-promotion-requests/{stablePromotionRequestID}';
};

export type GetPackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request retrieved successfully';
        data: {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        };
    };
};

export type GetPackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = GetPackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses[keyof GetPackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponses];

export type GetPackagesByFullPackageNameRoleAssignmentsData = {
    body?: never;
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/role-assignments';
};

export type GetPackagesByFullPackageNameRoleAssignmentsErrors = {
    /**
     * You do not have permission to view role assignments for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to view role assignments for this package';
    };
};

export type GetPackagesByFullPackageNameRoleAssignmentsError = GetPackagesByFullPackageNameRoleAssignmentsErrors[keyof GetPackagesByFullPackageNameRoleAssignmentsErrors];

export type GetPackagesByFullPackageNameRoleAssignmentsResponses = {
    /**
     * Role assignments retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Role assignments retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            user_id: number;
            role: 'ADMIN' | 'MAINTAINER' | 'DEVELOPER' | 'VIEWER';
            created_at: number;
            user_username: string;
            user_display_name: string | null;
            publisher_role: string | null;
        }>;
    };
};

export type GetPackagesByFullPackageNameRoleAssignmentsResponse = GetPackagesByFullPackageNameRoleAssignmentsResponses[keyof GetPackagesByFullPackageNameRoleAssignmentsResponses];

export type PostPackagesByFullPackageNameRoleAssignmentsData = {
    body: {
        user_id: number;
        role: 'ADMIN' | 'MAINTAINER' | 'DEVELOPER' | 'VIEWER';
    };
    path: {
        fullPackageName: string;
    };
    query?: never;
    url: '/packages/{fullPackageName}/role-assignments';
};

export type PostPackagesByFullPackageNameRoleAssignmentsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to manage role assignments for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to manage role assignments for this package';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * User already has a role assignment for this package
     */
    409: {
        success: false;
        code: 409;
        message: 'User already has a role assignment for this package';
    };
};

export type PostPackagesByFullPackageNameRoleAssignmentsError = PostPackagesByFullPackageNameRoleAssignmentsErrors[keyof PostPackagesByFullPackageNameRoleAssignmentsErrors];

export type PostPackagesByFullPackageNameRoleAssignmentsResponses = {
    /**
     * Role assignment created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Role assignment created successfully';
        data: null;
    };
};

export type PostPackagesByFullPackageNameRoleAssignmentsResponse = PostPackagesByFullPackageNameRoleAssignmentsResponses[keyof PostPackagesByFullPackageNameRoleAssignmentsResponses];

export type DeletePackagesByFullPackageNameRoleAssignmentsByUserIdData = {
    body?: never;
    path: {
        fullPackageName: string;
        userId: number;
    };
    query?: never;
    url: '/packages/{fullPackageName}/role-assignments/{userId}';
};

export type DeletePackagesByFullPackageNameRoleAssignmentsByUserIdErrors = {
    /**
     * You do not have permission to manage role assignments for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to manage role assignments for this package';
    };
    /**
     * Role assignment not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Role assignment not found';
    };
};

export type DeletePackagesByFullPackageNameRoleAssignmentsByUserIdError = DeletePackagesByFullPackageNameRoleAssignmentsByUserIdErrors[keyof DeletePackagesByFullPackageNameRoleAssignmentsByUserIdErrors];

export type DeletePackagesByFullPackageNameRoleAssignmentsByUserIdResponses = {
    /**
     * Role assignment deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Role assignment deleted successfully';
        data: null;
    };
};

export type DeletePackagesByFullPackageNameRoleAssignmentsByUserIdResponse = DeletePackagesByFullPackageNameRoleAssignmentsByUserIdResponses[keyof DeletePackagesByFullPackageNameRoleAssignmentsByUserIdResponses];

export type PutPackagesByFullPackageNameRoleAssignmentsByUserIdData = {
    body: {
        role: 'ADMIN' | 'MAINTAINER' | 'DEVELOPER' | 'VIEWER';
    };
    path: {
        fullPackageName: string;
        userId: number;
    };
    query?: never;
    url: '/packages/{fullPackageName}/role-assignments/{userId}';
};

export type PutPackagesByFullPackageNameRoleAssignmentsByUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You do not have permission to manage role assignments for this package
     */
    403: {
        success: false;
        code: 403;
        message: 'You do not have permission to manage role assignments for this package';
    };
    /**
     * Role assignment not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Role assignment not found';
    };
};

export type PutPackagesByFullPackageNameRoleAssignmentsByUserIdError = PutPackagesByFullPackageNameRoleAssignmentsByUserIdErrors[keyof PutPackagesByFullPackageNameRoleAssignmentsByUserIdErrors];

export type PutPackagesByFullPackageNameRoleAssignmentsByUserIdResponses = {
    /**
     * Role assignment updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Role assignment updated successfully';
        data: null;
    };
};

export type PutPackagesByFullPackageNameRoleAssignmentsByUserIdResponse = PutPackagesByFullPackageNameRoleAssignmentsByUserIdResponses[keyof PutPackagesByFullPackageNameRoleAssignmentsByUserIdResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'developer' | 'user';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body: {
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'developer' | 'user';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersByUserIdErrors = {
    /**
     * Cannot delete user while they own publishers
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete user while they own publishers';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersByUserIdError = DeleteAdminUsersByUserIdErrors[keyof DeleteAdminUsersByUserIdErrors];

export type DeleteAdminUsersByUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersByUserIdResponse = DeleteAdminUsersByUserIdResponses[keyof DeleteAdminUsersByUserIdResponses];

export type GetAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersByUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersByUserIdError = GetAdminUsersByUserIdErrors[keyof GetAdminUsersByUserIdErrors];

export type GetAdminUsersByUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type GetAdminUsersByUserIdResponse = GetAdminUsersByUserIdResponses[keyof GetAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdData = {
    body: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'developer' | 'user';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersByUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersByUserIdError = PutAdminUsersByUserIdErrors[keyof PutAdminUsersByUserIdErrors];

export type PutAdminUsersByUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type PutAdminUsersByUserIdResponse = PutAdminUsersByUserIdResponses[keyof PutAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdPasswordData = {
    body: {
        /**
         * New password for the account
         */
        password: string;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersByUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersByUserIdPasswordError = PutAdminUsersByUserIdPasswordErrors[keyof PutAdminUsersByUserIdPasswordErrors];

export type PutAdminUsersByUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersByUserIdPasswordResponse = PutAdminUsersByUserIdPasswordResponses[keyof PutAdminUsersByUserIdPasswordResponses];

export type GetAdminOsReleasesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
    };
    url: '/admin/os-releases';
};

export type GetAdminOsReleasesResponses = {
    /**
     * OS releases retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'OS releases retrieved';
        data: Array<{
            id: number;
            version: string;
            changelog: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        }>;
    };
};

export type GetAdminOsReleasesResponse = GetAdminOsReleasesResponses[keyof GetAdminOsReleasesResponses];

export type PostAdminOsReleasesData = {
    body: {
        changelog: string;
    };
    path?: never;
    query?: never;
    url: '/admin/os-releases';
};

export type PostAdminOsReleasesResponses = {
    /**
     * OS release creation task enqueued
     */
    202: {
        success: true;
        code: 202;
        message: 'OS release creation task enqueued';
        data: {
            id: number;
            version: string;
            changelog: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        };
    };
};

export type PostAdminOsReleasesResponse = PostAdminOsReleasesResponses[keyof PostAdminOsReleasesResponses];

export type GetAdminOsReleasesByVersionData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/admin/os-releases/{version}';
};

export type GetAdminOsReleasesByVersionErrors = {
    /**
     * OS release not found
     */
    404: {
        success: false;
        code: 404;
        message: 'OS release not found';
    };
};

export type GetAdminOsReleasesByVersionError = GetAdminOsReleasesByVersionErrors[keyof GetAdminOsReleasesByVersionErrors];

export type GetAdminOsReleasesByVersionResponses = {
    /**
     * OS release retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'OS release retrieved';
        data: {
            id: number;
            version: string;
            changelog: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        };
    };
};

export type GetAdminOsReleasesByVersionResponse = GetAdminOsReleasesByVersionResponses[keyof GetAdminOsReleasesByVersionResponses];

export type PutAdminOsReleasesByVersionData = {
    body: {
        changelog?: string;
    };
    path: {
        version: string;
    };
    query?: never;
    url: '/admin/os-releases/{version}';
};

export type PutAdminOsReleasesByVersionErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * OS release not found
     */
    404: {
        success: false;
        code: 404;
        message: 'OS release not found';
    };
};

export type PutAdminOsReleasesByVersionError = PutAdminOsReleasesByVersionErrors[keyof PutAdminOsReleasesByVersionErrors];

export type PutAdminOsReleasesByVersionResponses = {
    /**
     * OS release updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'OS release updated successfully';
        data: null;
    };
};

export type PutAdminOsReleasesByVersionResponse = PutAdminOsReleasesByVersionResponses[keyof PutAdminOsReleasesByVersionResponses];

export type GetAdminOsReleasesByVersionPublishingLogsData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/admin/os-releases/{version}/publishing-logs';
};

export type GetAdminOsReleasesByVersionPublishingLogsErrors = {
    /**
     * OS release not found / Log file not found for this OS release publishing task
     */
    404: {
        success: false;
        code: 404;
        message: 'OS release not found / Log file not found for this OS release publishing task';
    };
};

export type GetAdminOsReleasesByVersionPublishingLogsError = GetAdminOsReleasesByVersionPublishingLogsErrors[keyof GetAdminOsReleasesByVersionPublishingLogsErrors];

export type GetAdminOsReleasesByVersionPublishingLogsResponses = {
    /**
     * Publishing logs retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'Publishing logs retrieved';
        data: {
            logs: string;
        };
    };
};

export type GetAdminOsReleasesByVersionPublishingLogsResponse = GetAdminOsReleasesByVersionPublishingLogsResponses[keyof GetAdminOsReleasesByVersionPublishingLogsResponses];

export type GetAdminTasksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/admin/tasks';
};

export type GetAdminTasksResponses = {
    /**
     * Scheduled tasks retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'Scheduled tasks retrieved';
        data: Array<{
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        }>;
    };
};

export type GetAdminTasksResponse = GetAdminTasksResponses[keyof GetAdminTasksResponses];

export type GetAdminTasksByTaskIdData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/admin/tasks/{taskID}';
};

export type GetAdminTasksByTaskIdErrors = {
    /**
     * Task with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID not found';
    };
};

export type GetAdminTasksByTaskIdError = GetAdminTasksByTaskIdErrors[keyof GetAdminTasksByTaskIdErrors];

export type GetAdminTasksByTaskIdResponses = {
    /**
     * Task retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task retrieved successfully';
        data: {
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        };
    };
};

export type GetAdminTasksByTaskIdResponse = GetAdminTasksByTaskIdResponses[keyof GetAdminTasksByTaskIdResponses];

export type GetAdminTasksByTaskIdLogsData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/admin/tasks/{taskID}/logs';
};

export type GetAdminTasksByTaskIdLogsErrors = {
    /**
     * Logs are not stored for this task
     */
    400: {
        success: false;
        code: 400;
        message: 'Logs are not stored for this task';
    };
    /**
     * Task with specified ID not found / Log file not found for this task
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID not found / Log file not found for this task';
    };
};

export type GetAdminTasksByTaskIdLogsError = GetAdminTasksByTaskIdLogsErrors[keyof GetAdminTasksByTaskIdLogsErrors];

export type GetAdminTasksByTaskIdLogsResponses = {
    /**
     * Task logs retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task logs retrieved successfully';
        data: {
            logs: string;
        };
    };
};

export type GetAdminTasksByTaskIdLogsResponse = GetAdminTasksByTaskIdLogsResponses[keyof GetAdminTasksByTaskIdLogsResponses];

export type GetAdminStablePromotionRequestsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
    };
    url: '/admin/stable-promotion-requests';
};

export type GetAdminStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending' | 'approved' | 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        }>;
    };
};

export type GetAdminStablePromotionRequestsResponse = GetAdminStablePromotionRequestsResponses[keyof GetAdminStablePromotionRequestsResponses];

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdData = {
    body?: never;
    path: {
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/admin/stable-promotion-requests/{stablePromotionRequestID}';
};

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdErrors = {
    /**
     * Stable promotion request not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Stable promotion request not found';
    };
};

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdError = GetAdminStablePromotionRequestsByStablePromotionRequestIdErrors[keyof GetAdminStablePromotionRequestsByStablePromotionRequestIdErrors];

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdResponses = {
    /**
     * Stable promotion request retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request retrieved successfully';
        data: {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending' | 'approved' | 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        };
    };
};

export type GetAdminStablePromotionRequestsByStablePromotionRequestIdResponse = GetAdminStablePromotionRequestsByStablePromotionRequestIdResponses[keyof GetAdminStablePromotionRequestsByStablePromotionRequestIdResponses];

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideData = {
    body: {
        status: 'approved' | 'denied';
        admin_note: string;
    };
    path: {
        stablePromotionRequestID: number;
    };
    query?: never;
    url: '/admin/stable-promotion-requests/{stablePromotionRequestID}/decide';
};

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Stable promotion request not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Stable promotion request not found';
    };
};

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideError = PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideErrors[keyof PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideErrors];

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponses = {
    /**
     * Decided on stable promotion request successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Decided on stable promotion request successfully';
        data: null;
    };
};

export type PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponse = PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponses[keyof PostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponses];

export type GetUsersSearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
    };
    url: '/users/search';
};

export type GetUsersSearchErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
};

export type GetUsersSearchError = GetUsersSearchErrors[keyof GetUsersSearchErrors];

export type GetUsersSearchResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            username: string;
            display_name: string;
        }>;
    };
};

export type GetUsersSearchResponse = GetUsersSearchResponses[keyof GetUsersSearchResponses];
