// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zGetPublicPackagesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Packages retrieved successfully
 */
export const zGetPublicPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Packages retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        flags: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        latest_stable_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        }),
        latest_testing_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        })
    }))
});

export const zGetPublicPackagesByPackageNameData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string().min(1)
    }),
    query: z.object({
        repo: z.enum([
            'leios-archive',
            'leios-testing',
            'leios-stable'
        ]).optional()
    }).optional()
});

/**
 * Package retrieved successfully
 */
export const zGetPublicPackagesByPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package retrieved successfully'),
    data: z.object({
        package: z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            name: z.string(),
            owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            flags: z.union([
                z.union([
                    z.string(),
                    z.number(),
                    z.boolean()
                ]),
                z.record(z.string(), z.unknown()),
                z.array(z.unknown())
            ]).nullable(),
            description: z.string(),
            homepage_url: z.string(),
            requires_patching: z.boolean(),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            latest_stable_release: z.object({
                amd64: z.string().nullable(),
                arm64: z.string().nullable()
            }),
            latest_testing_release: z.object({
                amd64: z.string().nullable(),
                arm64: z.string().nullable()
            })
        }),
        releases: z.object({
            'leios-archive': z.record(z.string(), z.object({
                amd64: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional(),
                arm64: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional(),
                all: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional()
            })),
            'leios-testing': z.record(z.string(), z.object({
                amd64: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional(),
                arm64: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional(),
                all: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional()
            })),
            'leios-stable': z.record(z.string(), z.object({
                amd64: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional(),
                arm64: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional(),
                all: z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum([
                        'amd64',
                        'arm64',
                        'all'
                    ]),
                    maintainer: z.string(),
                    description: z.string()
                }).optional()
            }))
        })
    })
});

export const zGetPublicPackagesByPackageNameReleasesData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string().min(1)
    }),
    query: z.object({
        repo: z.enum([
            'leios-archive',
            'leios-testing',
            'leios-stable'
        ]).optional()
    }).optional()
});

/**
 * Package releases retrieved successfully
 */
export const zGetPublicPackagesByPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package releases retrieved successfully'),
    data: z.object({
        'leios-archive': z.record(z.string(), z.object({
            amd64: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional(),
            arm64: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional(),
            all: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional()
        })),
        'leios-testing': z.record(z.string(), z.object({
            amd64: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional(),
            arm64: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional(),
            all: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional()
        })),
        'leios-stable': z.record(z.string(), z.object({
            amd64: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional(),
            arm64: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional(),
            all: z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum([
                    'amd64',
                    'arm64',
                    'all'
                ]),
                maintainer: z.string(),
                description: z.string()
            }).optional()
        }))
    })
});

export const zPostAuthLoginData = z.object({
    body: z.object({
        username: z.string(),
        password: z.string()
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        token: z.string()
    })
});

export const zGetAuthSessionData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Session info retrieved successfully
 */
export const zGetAuthSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session info retrieved successfully'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPostAuthLogoutData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

export const zPostAuthResetPasswordData = z.object({
    body: z.object({
        reset_token: z.string().min(1),
        new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Password has been reset successfully
 */
export const zPostAuthResetPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password has been reset successfully'),
    data: z.null()
});

export const zPostAuthResetPasswordRequestData = z.object({
    body: z.object({
        email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * If the username exists, a password reset has been requested
 */
export const zPostAuthResetPasswordRequestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('If the username exists, a password reset has been requested'),
    data: z.null()
});

export const zDeleteAccountData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Account deleted successfully
 */
export const zDeleteAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account deleted successfully'),
    data: z.null()
});

export const zGetAccountData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Account information retrieved successfully
 */
export const zGetAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zPutAccountData = z.object({
    body: z.object({
        username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/).optional(),
        display_name: z.string().optional(),
        email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/).optional()
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Account information updated successfully
 */
export const zPutAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information updated successfully'),
    data: z.null()
});

export const zPutAccountPasswordData = z.object({
    body: z.object({
        current_password: z.string(),
        new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Password changed successfully
 */
export const zPutAccountPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password changed successfully'),
    data: z.null()
});

export const zGetAccountApikeysData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * API keys retrieved successfully
 */
export const zGetAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API keys retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    }))
});

export const zPostAccountApikeysData = z.object({
    body: z.object({
        description: z.string().min(1).max(255),
        expires_at: z.union([
            z.literal('7d'),
            z.literal('30d'),
            z.literal('90d'),
            z.literal('180d'),
            z.literal('365d')
        ]).nullable()
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * API key created successfully
 */
export const zPostAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key created successfully'),
    data: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zDeleteAccountApikeysByApiKeyIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        apiKeyID: z.string().min(1).max(255)
    }),
    query: z.never().optional()
});

/**
 * API key deleted successfully
 */
export const zDeleteAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key deleted successfully'),
    data: z.null()
});

export const zGetAccountApikeysByApiKeyIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        apiKeyID: z.string().min(1).max(255)
    }),
    query: z.never().optional()
});

/**
 * API key retrieved successfully
 */
export const zGetAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key retrieved successfully'),
    data: z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    })
});

export const zGetDevPackagesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Packages retrieved successfully
 */
export const zGetDevPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Packages retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        flags: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        latest_stable_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        }),
        latest_testing_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        })
    }))
});

export const zPostDevPackagesData = z.object({
    body: z.object({
        name: z.string().min(2).max(63).regex(/^[a-z0-9][a-z0-9+.-]*[a-z0-9]$/),
        description: z.string().min(1).max(500),
        homepage_url: z.url(),
        requires_patching: z.boolean().optional()
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Package created successfully
 */
export const zPostDevPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package created successfully'),
    data: z.null()
});

export const zGetDevPackagesByPackageNameData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package retrieved successfully
 */
export const zGetDevPackagesByPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        flags: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        latest_stable_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        }),
        latest_testing_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        })
    })
});

export const zPutDevPackagesByPackageNameData = z.object({
    body: z.object({
        description: z.string().min(1).max(500).optional(),
        homepage_url: z.url().optional(),
        requires_patching: z.boolean().optional()
    }).optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package updated successfully
 */
export const zPutDevPackagesByPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package updated successfully'),
    data: z.null()
});

export const zGetDevPackagesByPackageNameReleasesData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package releases retrieved successfully
 */
export const zGetDevPackagesByPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package releases retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architectures: z.object({
            amd64: z.boolean(),
            arm64: z.boolean(),
            is_all: z.boolean()
        }),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        changelog: z.string()
    }))
});

export const zPostDevPackagesByPackageNameReleasesData = z.object({
    body: z.object({
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
        changelog: z.string().min(1).max(10000)
    }).optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package release created successfully
 */
export const zPostDevPackagesByPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release created successfully'),
    data: z.null()
});

export const zGetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.never().optional()
});

/**
 * Package release retrieved successfully
 */
export const zGetDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architectures: z.object({
            amd64: z.boolean(),
            arm64: z.boolean(),
            is_all: z.boolean()
        }),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        changelog: z.string()
    })
});

export const zPutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchData = z.object({
    body: z.object({
        changelog: z.string().min(1).max(10000).optional()
    }).optional(),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.never().optional()
});

/**
 * Package release updated successfully
 */
export const zPutDevPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release updated successfully'),
    data: z.null()
});

export const zPostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchData = z.object({
    body: z.object({
        file: z.string().min(1).max(1073741824)
    }).optional(),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
        arch: z.enum([
            'amd64',
            'arm64',
            'all'
        ])
    }),
    query: z.never().optional()
});

/**
 * Package release file uploaded successfully
 */
export const zPostDevPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release file uploaded successfully'),
    data: z.null()
});

export const zGetDevPackagesByPackageNameStablePromotionRequestsData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.object({
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]).optional()
    }).optional()
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetDevPackagesByPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.null(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        })
    ]))
});

export const zPostDevPackagesByPackageNameStablePromotionRequestsData = z.object({
    body: z.object({
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991)
    }).optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Stable promotion request submitted
 */
export const zPostDevPackagesByPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Stable promotion request submitted'),
    data: z.object({
        id: z.number()
    })
});

export const zDeleteDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string(),
        stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Stable promotion request deleted successfully
 */
export const zDeleteDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request deleted successfully'),
    data: z.record(z.string(), z.unknown())
});

export const zGetDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string(),
        stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Stable promotion request retrieved successfully
 */
export const zGetDevPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request retrieved successfully'),
    data: z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.null(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        })
    ])
});

export const zGetDevTasksData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.int().gte(1).lte(100).optional().default(10),
        offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
        order: z.enum(['newest', 'oldest']).optional(),
        searchString: z.string().optional()
    }).optional()
});

/**
 * Scheduled tasks retrieved
 */
export const zGetDevTasksResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Scheduled tasks retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        message: z.string().nullable()
    }))
});

export const zGetDevTasksByTaskIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        taskID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Task retrieved successfully
 */
export const zGetDevTasksByTaskIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        message: z.string().nullable()
    })
});

export const zGetDevTasksByTaskIdLogsData = z.object({
    body: z.never().optional(),
    path: z.object({
        taskID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Task logs retrieved successfully
 */
export const zGetDevTasksByTaskIdLogsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task logs retrieved successfully'),
    data: z.object({
        logs: z.string()
    })
});

export const zGetAdminUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]).optional(),
        search: z.string().min(1).max(64).optional(),
        limit: z.int().gte(1).lte(100).optional(),
        offset: z.int().gte(0).lte(9007199254740991).optional()
    }).optional()
});

/**
 * Users retrieved successfully
 */
export const zGetAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Users retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    }))
});

export const zPostAdminUsersData = z.object({
    body: z.object({
        username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/),
        display_name: z.string().min(1).max(64),
        email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]).optional(),
        password: z.string().min(8).max(128)
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User created successfully
 */
export const zPostAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('User created successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zDeleteAdminUsersByUserIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * User deleted successfully
 */
export const zDeleteAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User deleted successfully'),
    data: z.null()
});

export const zGetAdminUsersByUserIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * User retrieved successfully
 */
export const zGetAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zPutAdminUsersByUserIdData = z.object({
    body: z.object({
        username: z.string().optional(),
        display_name: z.string().optional(),
        email: z.string().optional(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]).optional()
    }).optional(),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * User updated successfully
 */
export const zPutAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User updated successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zPutAdminUsersByUserIdPasswordData = z.object({
    body: z.object({
        password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
    }).optional(),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Password reset successfully
 */
export const zPutAdminUsersByUserIdPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password reset successfully'),
    data: z.null()
});

export const zGetAdminPackagesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Packages retrieved successfully
 */
export const zGetAdminPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Packages retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        flags: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        latest_stable_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        }),
        latest_testing_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        })
    }))
});

export const zPostAdminPackagesData = z.object({
    body: z.object({
        name: z.string().min(2).max(63).regex(/^[a-z0-9][a-z0-9+.-]*[a-z0-9]$/),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        description: z.string().min(1).max(500),
        homepage_url: z.url(),
        requires_patching: z.boolean().optional()
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Package created successfully
 */
export const zPostAdminPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package created successfully'),
    data: z.null()
});

export const zDeleteAdminPackagesByPackageNameData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package deleted successfully
 */
export const zDeleteAdminPackagesByPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package deleted successfully'),
    data: z.null()
});

export const zGetAdminPackagesByPackageNameData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package retrieved successfully
 */
export const zGetAdminPackagesByPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        flags: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        latest_stable_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        }),
        latest_testing_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        })
    })
});

export const zPutAdminPackagesByPackageNameData = z.object({
    body: z.object({
        description: z.string().min(1).max(500).optional(),
        homepage_url: z.url().optional(),
        requires_patching: z.boolean().optional()
    }).optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package updated successfully
 */
export const zPutAdminPackagesByPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package updated successfully'),
    data: z.null()
});

export const zGetAdminPackagesByPackageNameReleasesData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package releases retrieved successfully
 */
export const zGetAdminPackagesByPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package releases retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architectures: z.object({
            amd64: z.boolean(),
            arm64: z.boolean(),
            is_all: z.boolean()
        }),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        changelog: z.string()
    }))
});

export const zPostAdminPackagesByPackageNameReleasesData = z.object({
    body: z.object({
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
        changelog: z.string().min(1).max(10000)
    }).optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Package release created successfully
 */
export const zPostAdminPackagesByPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release created successfully'),
    data: z.null()
});

export const zDeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.never().optional()
});

/**
 * Package release deleted successfully
 */
export const zDeleteAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release deleted successfully'),
    data: z.null()
});

export const zGetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.never().optional()
});

/**
 * Package release retrieved successfully
 */
export const zGetAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architectures: z.object({
            amd64: z.boolean(),
            arm64: z.boolean(),
            is_all: z.boolean()
        }),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        changelog: z.string()
    })
});

export const zPutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchData = z.object({
    body: z.object({
        changelog: z.string().min(1).max(10000).optional()
    }).optional(),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.never().optional()
});

/**
 * Package release updated successfully
 */
export const zPutAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release updated successfully'),
    data: z.null()
});

export const zPostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchData = z.object({
    body: z.object({
        file: z.string().min(1).max(1073741824)
    }).optional(),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
        arch: z.enum([
            'amd64',
            'arm64',
            'all'
        ])
    }),
    query: z.never().optional()
});

/**
 * Package release file uploaded successfully
 */
export const zPostAdminPackagesByPackageNameReleasesByVersionWithLeiosPatchByArchResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release file uploaded successfully'),
    data: z.null()
});

export const zGetAdminPackagesByPackageNameStablePromotionRequestsData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.object({
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]).optional()
    }).optional()
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetAdminPackagesByPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.null(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        })
    ]))
});

export const zPostAdminPackagesByPackageNameStablePromotionRequestsData = z.object({
    body: z.object({
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991)
    }).optional(),
    path: z.object({
        packageName: z.string()
    }),
    query: z.never().optional()
});

/**
 * Stable promotion request submitted
 */
export const zPostAdminPackagesByPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Stable promotion request submitted'),
    data: z.object({
        id: z.number()
    })
});

export const zDeleteAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string(),
        stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Stable promotion request deleted successfully
 */
export const zDeleteAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request deleted successfully'),
    data: z.record(z.string(), z.unknown())
});

export const zGetAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        packageName: z.string(),
        stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Stable promotion request retrieved successfully
 */
export const zGetAdminPackagesByPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request retrieved successfully'),
    data: z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.null(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        })
    ])
});

export const zGetAdminOsReleasesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.int().gte(1).lte(100).optional().default(10),
        offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
        order: z.enum(['newest', 'oldest']).optional()
    }).optional()
});

/**
 * OS releases retrieved
 */
export const zGetAdminOsReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS releases retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        changelog: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        published_at: z.number().nullable(),
        publishing_status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ])
    }))
});

export const zPostAdminOsReleasesData = z.object({
    body: z.object({
        changelog: z.string().min(1).max(10000)
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OS release creation task enqueued
 */
export const zPostAdminOsReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(202),
    message: z.literal('OS release creation task enqueued'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        changelog: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        published_at: z.number().nullable(),
        publishing_status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ])
    })
});

export const zGetAdminOsReleasesByVersionData = z.object({
    body: z.never().optional(),
    path: z.object({
        version: z.string().regex(/^\d{4}\.\d{2}\.\d{3}$/)
    }),
    query: z.never().optional()
});

/**
 * OS release retrieved
 */
export const zGetAdminOsReleasesByVersionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS release retrieved'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        changelog: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        published_at: z.number().nullable(),
        publishing_status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ])
    })
});

export const zPutAdminOsReleasesByVersionData = z.object({
    body: z.object({
        changelog: z.string().min(1).max(10000).optional()
    }).optional(),
    path: z.object({
        version: z.string().regex(/^\d{4}\.\d{2}\.\d{3}$/)
    }),
    query: z.never().optional()
});

/**
 * OS release updated successfully
 */
export const zPutAdminOsReleasesByVersionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS release updated successfully'),
    data: z.null()
});

export const zGetAdminOsReleasesByVersionPublishingLogsData = z.object({
    body: z.never().optional(),
    path: z.object({
        version: z.string().regex(/^\d{4}\.\d{2}\.\d{3}$/)
    }),
    query: z.never().optional()
});

/**
 * Publishing logs retrieved
 */
export const zGetAdminOsReleasesByVersionPublishingLogsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Publishing logs retrieved'),
    data: z.object({
        logs: z.string()
    })
});

export const zGetAdminStablePromotionRequestsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.int().gte(1).lte(100).optional().default(10),
        offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
        order: z.enum(['newest', 'oldest']).optional()
    }).optional()
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetAdminStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        admin_note: z.string().nullable(),
        package_name: z.string(),
        package_release_version: z.string()
    }))
});

export const zGetAdminStablePromotionRequestsByStablePromotionRequestIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Stable promotion request retrieved successfully
 */
export const zGetAdminStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        admin_note: z.string().nullable(),
        package_name: z.string(),
        package_release_version: z.string()
    })
});

export const zPostAdminStablePromotionRequestsByStablePromotionRequestIdDecideData = z.object({
    body: z.object({
        status: z.enum(['approved', 'denied']),
        admin_note: z.string()
    }).optional(),
    path: z.object({
        stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Decided on stable promotion request successfully
 */
export const zPostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Decided on stable promotion request successfully'),
    data: z.null()
});

export const zGetAdminTasksData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.int().gte(1).lte(100).optional().default(10),
        offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
        order: z.enum(['newest', 'oldest']).optional(),
        searchString: z.string().optional()
    }).optional()
});

/**
 * Scheduled tasks retrieved
 */
export const zGetAdminTasksResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Scheduled tasks retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        message: z.string().nullable()
    }))
});

export const zGetAdminTasksByTaskIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        taskID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Task retrieved successfully
 */
export const zGetAdminTasksByTaskIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        message: z.string().nullable()
    })
});

export const zGetAdminTasksByTaskIdLogsData = z.object({
    body: z.never().optional(),
    path: z.object({
        taskID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.never().optional()
});

/**
 * Task logs retrieved successfully
 */
export const zGetAdminTasksByTaskIdLogsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task logs retrieved successfully'),
    data: z.object({
        logs: z.string()
    })
});
