// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zPostAuthLoginBody = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        token: z.string()
    })
});

/**
 * Session info retrieved successfully
 */
export const zGetAuthSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session info retrieved successfully'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

export const zPostAuthResetPasswordBody = z.object({
    reset_token: z.string().min(1),
    new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

/**
 * Password has been reset successfully
 */
export const zPostAuthResetPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password has been reset successfully'),
    data: z.null()
});

export const zPostAuthResetPasswordRequestBody = z.object({
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)
});

/**
 * If the username exists, a password reset has been requested
 */
export const zPostAuthResetPasswordRequestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('If the username exists, a password reset has been requested'),
    data: z.null()
});

/**
 * Account deleted successfully
 */
export const zDeleteAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account deleted successfully'),
    data: z.null()
});

/**
 * Account information retrieved successfully
 */
export const zGetAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPutAccountBody = z.object({
    username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/).optional(),
    display_name: z.string().optional(),
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/).optional()
}).and(z.object({
    current_password: z.string().min(1)
}));

/**
 * Account information updated successfully
 */
export const zPutAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information updated successfully'),
    data: z.null()
});

export const zPutAccountPasswordBody = z.object({
    current_password: z.string(),
    new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

/**
 * Password changed successfully
 */
export const zPutAccountPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password changed successfully'),
    data: z.null()
});

/**
 * API keys retrieved successfully
 */
export const zGetAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API keys retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    }))
});

export const zPostAccountApikeysBody = z.object({
    description: z.string().min(1).max(255),
    expires_at: z.union([
        z.literal('7d'),
        z.literal('30d'),
        z.literal('90d'),
        z.literal('180d'),
        z.literal('365d')
    ]).nullable()
});

/**
 * API key created successfully
 */
export const zPostAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key created successfully'),
    data: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zDeleteAccountApikeysByApiKeyIdPath = z.object({
    apiKeyID: z.string().min(1).max(255)
});

/**
 * API key deleted successfully
 */
export const zDeleteAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key deleted successfully'),
    data: z.null()
});

export const zGetAccountApikeysByApiKeyIdPath = z.object({
    apiKeyID: z.string().min(1).max(255)
});

/**
 * API key retrieved successfully
 */
export const zGetAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key retrieved successfully'),
    data: z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    })
});

export const zGetPublishersQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(10),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    searchString: z.string().min(3).optional(),
    onlyMembershipByMe: z.boolean().optional().default(false)
});

/**
 * Publishers retrieved successfully
 */
export const zGetPublishersResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Publishers retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        display_name: z.string(),
        description: z.string(),
        homepage_url: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    }))
});

export const zPostPublishersBody = z.object({
    name: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/),
    display_name: z.string().min(1).max(200),
    description: z.string().min(1).max(500),
    homepage_url: z.url().max(500)
});

/**
 * Publisher created successfully
 */
export const zPostPublishersResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Publisher created successfully'),
    data: z.object({
        id: z.int().gt(0).lte(9007199254740991)
    })
});

export const zDeletePublishersByPublisherNamePath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/)
});

/**
 * Publisher deleted successfully
 */
export const zDeletePublishersByPublisherNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Publisher deleted successfully'),
    data: z.null()
});

export const zGetPublishersByPublisherNamePath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/)
});

/**
 * Publisher retrieved successfully
 */
export const zGetPublishersByPublisherNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Publisher retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        display_name: z.string(),
        description: z.string(),
        homepage_url: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPutPublishersByPublisherNameBody = z.object({
    display_name: z.string().min(1).max(200).optional(),
    description: z.string().min(1).max(500).optional(),
    homepage_url: z.url().max(500).optional()
});

export const zPutPublishersByPublisherNamePath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/)
});

/**
 * Publisher updated successfully
 */
export const zPutPublishersByPublisherNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Publisher updated successfully'),
    data: z.null()
});

export const zPostPublishersByPublisherNameTransferOwnershipBody = z.object({
    new_owner_user_id: z.int().gt(0).lte(9007199254740991)
});

export const zPostPublishersByPublisherNameTransferOwnershipPath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/)
});

/**
 * Publisher ownership transferred successfully
 */
export const zPostPublishersByPublisherNameTransferOwnershipResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Publisher ownership transferred successfully'),
    data: z.null()
});

export const zGetPublishersByPublisherNameMembersPath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/)
});

/**
 * Members retrieved successfully
 */
export const zGetPublishersByPublisherNameMembersResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Members retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        role: z.enum([
            'ADMIN',
            'MAINTAINER',
            'DEVELOPER',
            'VIEWER'
        ]),
        is_publicly_hidden: z.boolean(),
        added_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_username: z.string(),
        user_display_name: z.string()
    }))
});

export const zPostPublishersByPublisherNameMembersBody = z.object({
    user_id: z.int().gt(0).lte(9007199254740991),
    role: z.enum([
        'ADMIN',
        'MAINTAINER',
        'DEVELOPER',
        'VIEWER'
    ]),
    is_publicly_hidden: z.boolean().optional().default(false)
});

export const zPostPublishersByPublisherNameMembersPath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/)
});

/**
 * Member added successfully
 */
export const zPostPublishersByPublisherNameMembersResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Member added successfully'),
    data: z.object({
        id: z.int().gt(0).lte(9007199254740991)
    })
});

export const zDeletePublishersByPublisherNameMembersByUserIdPath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/),
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Member removed successfully
 */
export const zDeletePublishersByPublisherNameMembersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Member removed successfully'),
    data: z.null()
});

export const zGetPublishersByPublisherNameMembersByUserIdPath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/),
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Member retrieved successfully
 */
export const zGetPublishersByPublisherNameMembersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Member retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        role: z.enum([
            'ADMIN',
            'MAINTAINER',
            'DEVELOPER',
            'VIEWER'
        ]),
        is_publicly_hidden: z.boolean(),
        added_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_username: z.string(),
        user_display_name: z.string()
    })
});

export const zPutPublishersByPublisherNameMembersByUserIdBody = z.object({
    role: z.enum([
        'ADMIN',
        'MAINTAINER',
        'DEVELOPER',
        'VIEWER'
    ]).optional(),
    is_publicly_hidden: z.boolean().optional()
});

export const zPutPublishersByPublisherNameMembersByUserIdPath = z.object({
    publisherName: z.string().min(2).max(50).regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/),
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Member updated successfully
 */
export const zPutPublishersByPublisherNameMembersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Member updated successfully'),
    data: z.null()
});

export const zGetPackagesQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(10),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    searchString: z.string().min(3).optional(),
    publisherID: z.int().gte(1).lte(9007199254740991).optional(),
    publisherName: z.string().min(1).optional(),
    onlyMembershipByMe: z.boolean().optional().default(false)
});

/**
 * Packages retrieved successfully
 */
export const zGetPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Packages retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        publisher_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        fullname: z.string(),
        top_level_alias: z.string().nullable(),
        display_name: z.string(),
        description: z.string(),
        homepage_url: z.string(),
        flags: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        requires_patching: z.boolean(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        latest_stable_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        }),
        latest_testing_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        })
    }))
});

export const zPostPackagesBody = z.object({
    publisher_id: z.int().gte(-9007199254740991).lte(9007199254740991),
    name: z.string().min(2).max(200).regex(/^[a-z0-9][a-z0-9.-]*[a-z0-9]$/),
    display_name: z.string().min(1).max(200),
    description: z.string().min(1).max(500),
    homepage_url: z.url().max(500),
    requires_patching: z.boolean().optional().default(false)
});

/**
 * Package created successfully
 */
export const zPostPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package created successfully'),
    data: z.null()
});

export const zDeletePackagesByFullPackageNamePath = z.object({
    fullPackageName: z.string()
});

/**
 * Package deleted successfully
 */
export const zDeletePackagesByFullPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package deleted successfully'),
    data: z.null()
});

export const zGetPackagesByFullPackageNamePath = z.object({
    fullPackageName: z.string()
});

/**
 * Package retrieved successfully
 */
export const zGetPackagesByFullPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        publisher_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        fullname: z.string(),
        top_level_alias: z.string().nullable(),
        display_name: z.string(),
        description: z.string(),
        homepage_url: z.string(),
        flags: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        requires_patching: z.boolean(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        latest_stable_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        }),
        latest_testing_release: z.object({
            amd64: z.string().nullable(),
            arm64: z.string().nullable()
        })
    })
});

export const zPutPackagesByFullPackageNameBody = z.object({
    display_name: z.string().min(1).max(200).optional(),
    description: z.string().min(1).max(500).optional(),
    homepage_url: z.url().max(500).optional(),
    requires_patching: z.boolean().optional().default(false)
});

export const zPutPackagesByFullPackageNamePath = z.object({
    fullPackageName: z.string()
});

/**
 * Package updated successfully
 */
export const zPutPackagesByFullPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package updated successfully'),
    data: z.null()
});

export const zGetPackagesByFullPackageNameReleasesPath = z.object({
    fullPackageName: z.string()
});

/**
 * Package releases retrieved successfully
 */
export const zGetPackagesByFullPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package releases retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version_with_leios_patch: z.string(),
        architectures: z.object({
            amd64: z.boolean(),
            arm64: z.boolean(),
            is_all: z.boolean()
        }),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        changelog: z.string()
    }))
});

export const zPostPackagesByFullPackageNameReleasesBody = z.object({
    version_with_leios_patch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
    changelog: z.string().min(1).max(10000)
});

export const zPostPackagesByFullPackageNameReleasesPath = z.object({
    fullPackageName: z.string()
});

/**
 * Package release created successfully
 */
export const zPostPackagesByFullPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release created successfully'),
    data: z.null()
});

export const zDeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchPath = z.object({
    fullPackageName: z.string(),
    version_with_leios_patch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
});

/**
 * Package release deleted successfully
 */
export const zDeletePackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release deleted successfully'),
    data: z.null()
});

export const zGetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchPath = z.object({
    fullPackageName: z.string(),
    version_with_leios_patch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
});

/**
 * Package release retrieved successfully
 */
export const zGetPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version_with_leios_patch: z.string(),
        architectures: z.object({
            amd64: z.boolean(),
            arm64: z.boolean(),
            is_all: z.boolean()
        }),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        changelog: z.string()
    })
});

export const zPutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchBody = z.object({
    changelog: z.string().min(1).max(10000).optional()
});

export const zPutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchPath = z.object({
    fullPackageName: z.string(),
    version_with_leios_patch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
});

/**
 * Package release updated successfully
 */
export const zPutPackagesByFullPackageNameReleasesByVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release updated successfully'),
    data: z.null()
});

export const zPostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchBody = z.object({
    file: z.string().min(1).max(1073741824)
});

export const zPostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchPath = z.object({
    fullPackageName: z.string(),
    version_with_leios_patch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
    arch: z.enum([
        'amd64',
        'arm64',
        'all'
    ])
});

/**
 * Package release file uploaded successfully
 */
export const zPostPackagesByFullPackageNameReleasesByVersionWithLeiosPatchByArchResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release file uploaded successfully'),
    data: z.null()
});

export const zGetPackagesByFullPackageNameStablePromotionRequestsPath = z.object({
    fullPackageName: z.string()
});

export const zGetPackagesByFullPackageNameStablePromotionRequestsQuery = z.object({
    status: z.enum([
        'pending',
        'approved',
        'denied'
    ]).optional()
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetPackagesByFullPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.null(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        })
    ]))
});

export const zPostPackagesByFullPackageNameStablePromotionRequestsBody = z.object({
    package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991)
});

export const zPostPackagesByFullPackageNameStablePromotionRequestsPath = z.object({
    fullPackageName: z.string()
});

/**
 * Stable promotion request submitted
 */
export const zPostPackagesByFullPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Stable promotion request submitted'),
    data: z.object({
        id: z.number()
    })
});

export const zDeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdPath = z.object({
    fullPackageName: z.string(),
    stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Stable promotion request deleted successfully
 */
export const zDeletePackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request deleted successfully'),
    data: z.null()
});

export const zGetPackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdPath = z.object({
    fullPackageName: z.string(),
    stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Stable promotion request retrieved successfully
 */
export const zGetPackagesByFullPackageNameStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request retrieved successfully'),
    data: z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.null(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            admin_note: z.string().nullable(),
            package_name: z.string(),
            package_release_version: z.string()
        })
    ])
});

export const zGetPackagesByFullPackageNameRoleAssignmentsPath = z.object({
    fullPackageName: z.string()
});

/**
 * Role assignments retrieved successfully
 */
export const zGetPackagesByFullPackageNameRoleAssignmentsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Role assignments retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        role: z.enum([
            'ADMIN',
            'MAINTAINER',
            'DEVELOPER',
            'VIEWER'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_username: z.string(),
        user_display_name: z.string().nullable(),
        publisher_role: z.string().nullable()
    }))
});

export const zPostPackagesByFullPackageNameRoleAssignmentsBody = z.object({
    user_id: z.int().gt(0).lte(9007199254740991),
    role: z.enum([
        'ADMIN',
        'MAINTAINER',
        'DEVELOPER',
        'VIEWER'
    ])
});

export const zPostPackagesByFullPackageNameRoleAssignmentsPath = z.object({
    fullPackageName: z.string()
});

/**
 * Role assignment created successfully
 */
export const zPostPackagesByFullPackageNameRoleAssignmentsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Role assignment created successfully'),
    data: z.null()
});

export const zDeletePackagesByFullPackageNameRoleAssignmentsByUserIdPath = z.object({
    fullPackageName: z.string(),
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Role assignment deleted successfully
 */
export const zDeletePackagesByFullPackageNameRoleAssignmentsByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Role assignment deleted successfully'),
    data: z.null()
});

export const zPutPackagesByFullPackageNameRoleAssignmentsByUserIdBody = z.object({
    role: z.enum([
        'ADMIN',
        'MAINTAINER',
        'DEVELOPER',
        'VIEWER'
    ])
});

export const zPutPackagesByFullPackageNameRoleAssignmentsByUserIdPath = z.object({
    fullPackageName: z.string(),
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Role assignment updated successfully
 */
export const zPutPackagesByFullPackageNameRoleAssignmentsByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Role assignment updated successfully'),
    data: z.null()
});

export const zGetAdminUsersQuery = z.object({
    role: z.enum([
        'admin',
        'developer',
        'user'
    ]).optional(),
    search: z.string().min(1).max(64).optional(),
    limit: z.int().gte(1).lte(100).optional(),
    offset: z.int().gte(0).lte(9007199254740991).optional()
});

/**
 * Users retrieved successfully
 */
export const zGetAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Users retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    }))
});

export const zPostAdminUsersBody = z.object({
    username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/),
    display_name: z.string().min(1).max(64),
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    role: z.enum([
        'admin',
        'developer',
        'user'
    ]).optional(),
    password: z.string().min(8).max(128)
});

/**
 * User created successfully
 */
export const zPostAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('User created successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zDeleteAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User deleted successfully
 */
export const zDeleteAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User deleted successfully'),
    data: z.null()
});

export const zGetAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User retrieved successfully
 */
export const zGetAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPutAdminUsersByUserIdBody = z.object({
    username: z.string().optional(),
    display_name: z.string().optional(),
    email: z.string().optional(),
    role: z.enum([
        'admin',
        'developer',
        'user'
    ]).optional()
});

export const zPutAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User updated successfully
 */
export const zPutAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User updated successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPutAdminUsersByUserIdPasswordBody = z.object({
    password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

export const zPutAdminUsersByUserIdPasswordPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Password reset successfully
 */
export const zPutAdminUsersByUserIdPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password reset successfully'),
    data: z.null()
});

export const zGetAdminOsReleasesQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(10),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    order: z.enum(['newest', 'oldest']).optional().default('newest')
});

/**
 * OS releases retrieved
 */
export const zGetAdminOsReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS releases retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        changelog: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        published_at: z.number().nullable(),
        publishing_status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ])
    }))
});

export const zPostAdminOsReleasesBody = z.object({
    changelog: z.string().min(1).max(10000)
});

/**
 * OS release creation task enqueued
 */
export const zPostAdminOsReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(202),
    message: z.literal('OS release creation task enqueued'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        changelog: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        published_at: z.number().nullable(),
        publishing_status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ])
    })
});

export const zGetAdminOsReleasesByVersionPath = z.object({
    version: z.string().regex(/^\d{4}\.\d{2}\.\d{3}$/)
});

/**
 * OS release retrieved
 */
export const zGetAdminOsReleasesByVersionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS release retrieved'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        changelog: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        published_at: z.number().nullable(),
        publishing_status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ])
    })
});

export const zPutAdminOsReleasesByVersionBody = z.object({
    changelog: z.string().min(1).max(10000).optional()
});

export const zPutAdminOsReleasesByVersionPath = z.object({
    version: z.string().regex(/^\d{4}\.\d{2}\.\d{3}$/)
});

/**
 * OS release updated successfully
 */
export const zPutAdminOsReleasesByVersionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS release updated successfully'),
    data: z.null()
});

export const zGetAdminOsReleasesByVersionPublishingLogsPath = z.object({
    version: z.string().regex(/^\d{4}\.\d{2}\.\d{3}$/)
});

/**
 * Publishing logs retrieved
 */
export const zGetAdminOsReleasesByVersionPublishingLogsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Publishing logs retrieved'),
    data: z.object({
        logs: z.string()
    })
});

export const zGetAdminTasksQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(10),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    order: z.enum(['newest', 'oldest']).optional().default('newest'),
    searchString: z.string().min(3).optional()
});

/**
 * Scheduled tasks retrieved
 */
export const zGetAdminTasksResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Scheduled tasks retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        message: z.string().nullable()
    }))
});

export const zGetAdminTasksByTaskIdPath = z.object({
    taskID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Task retrieved successfully
 */
export const zGetAdminTasksByTaskIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.union([
            z.union([
                z.string(),
                z.number(),
                z.boolean()
            ]),
            z.record(z.string(), z.unknown()),
            z.array(z.unknown())
        ]).nullable(),
        message: z.string().nullable()
    })
});

export const zGetAdminTasksByTaskIdLogsPath = z.object({
    taskID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Task logs retrieved successfully
 */
export const zGetAdminTasksByTaskIdLogsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task logs retrieved successfully'),
    data: z.object({
        logs: z.string()
    })
});

export const zGetAdminStablePromotionRequestsQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(10),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    order: z.enum(['newest', 'oldest']).optional().default('newest')
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetAdminStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        admin_note: z.string().nullable(),
        package_name: z.string(),
        package_release_version: z.string()
    }))
});

export const zGetAdminStablePromotionRequestsByStablePromotionRequestIdPath = z.object({
    stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Stable promotion request retrieved successfully
 */
export const zGetAdminStablePromotionRequestsByStablePromotionRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        admin_note: z.string().nullable(),
        package_name: z.string(),
        package_release_version: z.string()
    })
});

export const zPostAdminStablePromotionRequestsByStablePromotionRequestIdDecideBody = z.object({
    status: z.enum(['approved', 'denied']),
    admin_note: z.string()
});

export const zPostAdminStablePromotionRequestsByStablePromotionRequestIdDecidePath = z.object({
    stablePromotionRequestID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Decided on stable promotion request successfully
 */
export const zPostAdminStablePromotionRequestsByStablePromotionRequestIdDecideResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Decided on stable promotion request successfully'),
    data: z.null()
});

export const zGetUsersSearchQuery = z.object({
    q: z.string().min(2).max(64),
    limit: z.int().gte(1).lte(50).optional().default(10)
});

/**
 * Users retrieved successfully
 */
export const zGetUsersSearchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Users retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string()
    }))
});
